create table if not exists public.mural_collections (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  year integer,
  description text,
  image_key text,
  status text not null default 'active' check (status in ('active','archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mural_collection_products (
  collection_id bigint not null references public.mural_collections(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  sort_order integer not null default 0,
  primary key (collection_id, product_id)
);

create table if not exists public.mural_posts (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('product','collection','notice')),
  status text not null default 'draft' check (status in ('draft','published','archived')),
  title text not null,
  subtitle text,
  body text,
  badge text,
  badge_tone text,
  image_key text,
  product_id bigint references public.products(id) on delete set null,
  collection_id bigint references public.mural_collections(id) on delete set null,
  notice_level text check (notice_level is null or notice_level in ('important','attention','info')),
  featured boolean not null default false,
  priority integer not null default 0 check (priority between 0 and 100),
  published_at timestamptz,
  expires_at timestamptz,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mural_posts_reference_check check (
    (kind = 'product' and product_id is not null and collection_id is null and notice_level is null)
    or (kind = 'collection' and collection_id is not null and product_id is null and notice_level is null)
    or (kind = 'notice' and product_id is null and collection_id is null and notice_level is not null)
  ),
  constraint mural_posts_expiry_check check (
    expires_at is null or published_at is null or expires_at > published_at
  )
);

create table if not exists public.mural_post_reads (
  post_id bigint not null references public.mural_posts(id) on delete cascade,
  user_id text not null check (char_length(user_id) between 1 and 100),
  read_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create index if not exists idx_mural_posts_feed
  on public.mural_posts(status, featured desc, priority desc, published_at desc, id desc);
create index if not exists idx_mural_posts_kind_date
  on public.mural_posts(kind, status, published_at desc);
create index if not exists idx_mural_posts_product_id
  on public.mural_posts(product_id);
create index if not exists idx_mural_posts_collection_id
  on public.mural_posts(collection_id);
create index if not exists idx_mural_reads_user
  on public.mural_post_reads(user_id, post_id);
create index if not exists idx_mural_collection_products_product_id
  on public.mural_collection_products(product_id);
create index if not exists idx_mural_collection_products_order
  on public.mural_collection_products(collection_id, sort_order, product_id);

alter table public.mural_collections enable row level security;
alter table public.mural_collection_products enable row level security;
alter table public.mural_posts enable row level security;
alter table public.mural_post_reads enable row level security;

revoke all on public.mural_collections from anon, authenticated;
revoke all on public.mural_collection_products from anon, authenticated;
revoke all on public.mural_posts from anon, authenticated;
revoke all on public.mural_post_reads from anon, authenticated;
