begin;

create table if not exists public.commerce_categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint commerce_categories_name_nonblank check (btrim(name) <> ''),
  constraint commerce_categories_slug_nonblank check (btrim(slug) <> '')
);

create unique index if not exists commerce_categories_slug_uq
  on public.commerce_categories (lower(btrim(slug)));

create table if not exists public.commerce_subcategories (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.commerce_categories(id) on delete restrict,
  name text not null,
  slug text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint commerce_subcategories_name_nonblank check (btrim(name) <> ''),
  constraint commerce_subcategories_slug_nonblank check (btrim(slug) <> ''),
  constraint commerce_subcategories_id_category_uq unique (id, category_id)
);

create unique index if not exists commerce_subcategories_category_slug_uq
  on public.commerce_subcategories (category_id, lower(btrim(slug)));

create index if not exists commerce_subcategories_category_idx
  on public.commerce_subcategories (category_id, is_active);

create table if not exists public.commerce_products (
  id bigint generated by default as identity primary key,
  name text not null,
  category_id bigint references public.commerce_categories(id) on delete restrict,
  subcategory_id bigint,
  temporal_type text not null default 'UNCLASSIFIED',
  edition_year integer,
  internal_status text not null default 'DRAFT',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint commerce_products_name_nonblank check (btrim(name) <> ''),
  constraint commerce_products_temporal_type_ck check (temporal_type in ('ANNUAL', 'PERMANENT', 'UNCLASSIFIED')),
  constraint commerce_products_internal_status_ck check (internal_status in ('DRAFT', 'ACTIVE', 'DISCONTINUED')),
  constraint commerce_products_year_range_ck check (edition_year is null or edition_year between 2000 and 2100),
  constraint commerce_products_annual_year_ck check (temporal_type <> 'ANNUAL' or edition_year is not null),
  constraint commerce_products_subcategory_requires_category_ck check (subcategory_id is null or category_id is not null),
  constraint commerce_products_subcategory_fk
    foreign key (subcategory_id, category_id)
    references public.commerce_subcategories(id, category_id)
    on delete restrict
);

create index if not exists commerce_products_category_idx
  on public.commerce_products (category_id, subcategory_id, internal_status);

create index if not exists commerce_products_temporal_idx
  on public.commerce_products (temporal_type, edition_year, internal_status);

create index if not exists commerce_products_name_idx
  on public.commerce_products (lower(name));

create table if not exists public.commerce_product_skus (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.commerce_products(id) on delete cascade,
  sku text not null,
  sku_type text not null default 'ALIAS',
  valid_from_year integer,
  valid_to_year integer,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint commerce_product_skus_sku_nonblank check (btrim(sku) <> ''),
  constraint commerce_product_skus_type_ck check (sku_type in ('CURRENT', 'HISTORICAL', 'ALIAS')),
  constraint commerce_product_skus_years_ck check (
    (valid_from_year is null or valid_from_year between 2000 and 2100)
    and (valid_to_year is null or valid_to_year between 2000 and 2100)
    and (valid_from_year is null or valid_to_year is null or valid_from_year <= valid_to_year)
  ),
  constraint commerce_product_skus_id_product_uq unique (id, product_id)
);

create unique index if not exists commerce_product_skus_sku_uq
  on public.commerce_product_skus (upper(btrim(sku)));

create unique index if not exists commerce_product_skus_one_current_uq
  on public.commerce_product_skus (product_id)
  where sku_type = 'CURRENT' and is_active = true;

create index if not exists commerce_product_skus_product_idx
  on public.commerce_product_skus (product_id, is_active, sku_type);

create table if not exists public.commerce_marketplaces (
  id bigint generated by default as identity primary key,
  code text not null,
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint commerce_marketplaces_code_nonblank check (btrim(code) <> ''),
  constraint commerce_marketplaces_name_nonblank check (btrim(name) <> '')
);

create unique index if not exists commerce_marketplaces_code_uq
  on public.commerce_marketplaces (upper(btrim(code)));

insert into public.commerce_marketplaces (code, name)
values
  ('SHOPEE', 'Shopee'),
  ('MERCADO_LIVRE', 'Mercado Livre'),
  ('AMAZON', 'Amazon')
on conflict do nothing;

create table if not exists public.commerce_listings (
  id bigint generated by default as identity primary key,
  marketplace_id bigint not null references public.commerce_marketplaces(id) on delete restrict,
  external_listing_id text,
  canonical_url text not null,
  source_url text,
  title text,
  listing_status text not null default 'UNKNOWN',
  sales_status text not null default 'UNKNOWN',
  video_status text not null default 'UNKNOWN',
  observed_year integer,
  source text not null default 'MANUAL',
  last_checked_at timestamptz,
  raw_metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint commerce_listings_url_nonblank check (btrim(canonical_url) <> ''),
  constraint commerce_listings_status_ck check (listing_status in ('UNKNOWN', 'ACTIVE', 'PAUSED', 'INACTIVE', 'REMOVED')),
  constraint commerce_listings_sales_status_ck check (sales_status in ('UNKNOWN', 'SELLING', 'NO_SALES')),
  constraint commerce_listings_video_status_ck check (video_status in ('UNKNOWN', 'ACTIVE', 'ABSENT', 'DISABLED')),
  constraint commerce_listings_source_ck check (source in ('MANUAL', 'EXCEL', 'API')),
  constraint commerce_listings_year_range_ck check (observed_year is null or observed_year between 2000 and 2100)
);

create unique index if not exists commerce_listings_external_id_uq
  on public.commerce_listings (marketplace_id, btrim(external_listing_id))
  where external_listing_id is not null and btrim(external_listing_id) <> '';

create unique index if not exists commerce_listings_url_uq
  on public.commerce_listings (marketplace_id, canonical_url);

create index if not exists commerce_listings_marketplace_status_idx
  on public.commerce_listings (marketplace_id, listing_status, sales_status);

create index if not exists commerce_listings_year_idx
  on public.commerce_listings (observed_year, marketplace_id);

create table if not exists public.commerce_listing_products (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.commerce_listings(id) on delete cascade,
  product_id bigint not null references public.commerce_products(id) on delete restrict,
  product_sku_id bigint,
  platform_sku text,
  variation_id text,
  variation_name text,
  relation_status text not null default 'UNKNOWN',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint commerce_listing_products_status_ck check (relation_status in ('UNKNOWN', 'ACTIVE', 'INACTIVE', 'REMOVED')),
  constraint commerce_listing_products_product_sku_fk
    foreign key (product_sku_id, product_id)
    references public.commerce_product_skus(id, product_id)
    on delete restrict
);

create unique index if not exists commerce_listing_products_identity_uq
  on public.commerce_listing_products (
    listing_id,
    product_id,
    coalesce(product_sku_id, 0),
    coalesce(upper(btrim(platform_sku)), ''),
    coalesce(btrim(variation_id), '')
  );

create index if not exists commerce_listing_products_product_idx
  on public.commerce_listing_products (product_id, relation_status, listing_id);

create index if not exists commerce_listing_products_listing_idx
  on public.commerce_listing_products (listing_id, relation_status, product_id);

create index if not exists commerce_listing_products_platform_sku_idx
  on public.commerce_listing_products (upper(btrim(platform_sku)))
  where platform_sku is not null and btrim(platform_sku) <> '';

create table if not exists public.commerce_import_batches (
  id bigint generated by default as identity primary key,
  marketplace_id bigint not null references public.commerce_marketplaces(id) on delete restrict,
  source_filename text not null,
  source_sha256 text,
  source_object_key text,
  status text not null default 'UPLOADED',
  sheet_count integer not null default 0,
  row_count integer not null default 0,
  matched_count integer not null default 0,
  conflict_count integer not null default 0,
  invalid_count integer not null default 0,
  created_by text,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint commerce_import_batches_filename_nonblank check (btrim(source_filename) <> ''),
  constraint commerce_import_batches_sha256_ck check (source_sha256 is null or source_sha256 ~ '^[0-9a-fA-F]{64}$'),
  constraint commerce_import_batches_status_ck check (status in ('UPLOADED', 'PARSED', 'REVIEW', 'COMMITTED', 'FAILED')),
  constraint commerce_import_batches_counts_ck check (
    sheet_count >= 0 and row_count >= 0 and matched_count >= 0 and conflict_count >= 0 and invalid_count >= 0
  )
);

create index if not exists commerce_import_batches_marketplace_idx
  on public.commerce_import_batches (marketplace_id, created_at desc);

create index if not exists commerce_import_batches_status_idx
  on public.commerce_import_batches (status, created_at desc);

create table if not exists public.commerce_import_rows (
  id bigint generated by default as identity primary key,
  batch_id bigint not null references public.commerce_import_batches(id) on delete cascade,
  sheet_name text not null,
  row_number integer not null,
  original_payload jsonb not null,
  normalized_payload jsonb,
  status text not null default 'PENDING',
  matched_product_id bigint references public.commerce_products(id) on delete set null,
  matched_listing_id bigint references public.commerce_listings(id) on delete set null,
  match_method text,
  match_score numeric(6,5),
  error_code text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint commerce_import_rows_sheet_nonblank check (btrim(sheet_name) <> ''),
  constraint commerce_import_rows_row_number_ck check (row_number > 0),
  constraint commerce_import_rows_status_ck check (status in ('PENDING', 'MATCHED', 'PROBABLE', 'NEW_PRODUCT', 'CONFLICT', 'INVALID', 'IGNORED', 'COMMITTED')),
  constraint commerce_import_rows_score_ck check (match_score is null or (match_score >= 0 and match_score <= 1)),
  constraint commerce_import_rows_position_uq unique (batch_id, sheet_name, row_number)
);

create index if not exists commerce_import_rows_batch_status_idx
  on public.commerce_import_rows (batch_id, status, row_number);

create index if not exists commerce_import_rows_matched_product_idx
  on public.commerce_import_rows (matched_product_id)
  where matched_product_id is not null;

create table if not exists public.commerce_reconciliation_candidates (
  id bigint generated by default as identity primary key,
  import_row_id bigint not null references public.commerce_import_rows(id) on delete cascade,
  product_id bigint not null references public.commerce_products(id) on delete cascade,
  match_method text not null,
  match_score numeric(6,5) not null,
  rank integer not null,
  is_confirmed boolean not null default false,
  created_at timestamptz not null default now(),
  constraint commerce_reconciliation_candidates_method_nonblank check (btrim(match_method) <> ''),
  constraint commerce_reconciliation_candidates_score_ck check (match_score >= 0 and match_score <= 1),
  constraint commerce_reconciliation_candidates_rank_ck check (rank > 0),
  constraint commerce_reconciliation_candidates_row_product_uq unique (import_row_id, product_id)
);

create index if not exists commerce_reconciliation_candidates_row_rank_idx
  on public.commerce_reconciliation_candidates (import_row_id, rank);

create table if not exists public.commerce_update_campaigns (
  id bigint generated by default as identity primary key,
  name text not null,
  source_year integer,
  target_year integer not null,
  status text not null default 'DRAFT',
  created_by text,
  created_at timestamptz not null default now(),
  opened_at timestamptz,
  closed_at timestamptz,
  constraint commerce_update_campaigns_name_nonblank check (btrim(name) <> ''),
  constraint commerce_update_campaigns_source_year_ck check (source_year is null or source_year between 2000 and 2100),
  constraint commerce_update_campaigns_target_year_ck check (target_year between 2000 and 2100),
  constraint commerce_update_campaigns_year_order_ck check (source_year is null or source_year < target_year),
  constraint commerce_update_campaigns_status_ck check (status in ('DRAFT', 'OPEN', 'CLOSED', 'ARCHIVED'))
);

create unique index if not exists commerce_update_campaigns_name_uq
  on public.commerce_update_campaigns (lower(btrim(name)));

create index if not exists commerce_update_campaigns_target_idx
  on public.commerce_update_campaigns (target_year, status);

create table if not exists public.commerce_update_items (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.commerce_update_campaigns(id) on delete cascade,
  listing_product_id bigint not null references public.commerce_listing_products(id) on delete restrict,
  overall_status text not null default 'NOT_CHECKED',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint commerce_update_items_status_ck check (overall_status in ('NOT_CHECKED', 'OK', 'NEEDS_UPDATE', 'IN_PROGRESS', 'BLOCKED', 'NOT_APPLICABLE')),
  constraint commerce_update_items_identity_uq unique (campaign_id, listing_product_id)
);

create index if not exists commerce_update_items_campaign_status_idx
  on public.commerce_update_items (campaign_id, overall_status, listing_product_id);

create table if not exists public.commerce_update_checks (
  id bigint generated by default as identity primary key,
  update_item_id bigint not null references public.commerce_update_items(id) on delete cascade,
  check_type text not null,
  is_required boolean not null default true,
  status text not null default 'NOT_CHECKED',
  detected_value text,
  expected_value text,
  notes text,
  checked_by text,
  checked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint commerce_update_checks_type_ck check (check_type in ('SKU', 'TITLE', 'DESCRIPTION', 'IMAGES', 'VIDEO', 'ATTRIBUTES')),
  constraint commerce_update_checks_status_ck check (status in ('NOT_CHECKED', 'OK', 'NEEDS_UPDATE', 'IN_PROGRESS', 'BLOCKED', 'NOT_APPLICABLE')),
  constraint commerce_update_checks_identity_uq unique (update_item_id, check_type)
);

create index if not exists commerce_update_checks_status_idx
  on public.commerce_update_checks (status, check_type, update_item_id);

create or replace function public.commerce_touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger commerce_categories_touch_updated_at
before update on public.commerce_categories
for each row execute function public.commerce_touch_updated_at();

create trigger commerce_subcategories_touch_updated_at
before update on public.commerce_subcategories
for each row execute function public.commerce_touch_updated_at();

create trigger commerce_products_touch_updated_at
before update on public.commerce_products
for each row execute function public.commerce_touch_updated_at();

create trigger commerce_product_skus_touch_updated_at
before update on public.commerce_product_skus
for each row execute function public.commerce_touch_updated_at();

create trigger commerce_marketplaces_touch_updated_at
before update on public.commerce_marketplaces
for each row execute function public.commerce_touch_updated_at();

create trigger commerce_listings_touch_updated_at
before update on public.commerce_listings
for each row execute function public.commerce_touch_updated_at();

create trigger commerce_listing_products_touch_updated_at
before update on public.commerce_listing_products
for each row execute function public.commerce_touch_updated_at();

create trigger commerce_import_rows_touch_updated_at
before update on public.commerce_import_rows
for each row execute function public.commerce_touch_updated_at();

create trigger commerce_update_items_touch_updated_at
before update on public.commerce_update_items
for each row execute function public.commerce_touch_updated_at();

create trigger commerce_update_checks_touch_updated_at
before update on public.commerce_update_checks
for each row execute function public.commerce_touch_updated_at();

alter table public.commerce_categories enable row level security;
alter table public.commerce_subcategories enable row level security;
alter table public.commerce_products enable row level security;
alter table public.commerce_product_skus enable row level security;
alter table public.commerce_marketplaces enable row level security;
alter table public.commerce_listings enable row level security;
alter table public.commerce_listing_products enable row level security;
alter table public.commerce_import_batches enable row level security;
alter table public.commerce_import_rows enable row level security;
alter table public.commerce_reconciliation_candidates enable row level security;
alter table public.commerce_update_campaigns enable row level security;
alter table public.commerce_update_items enable row level security;
alter table public.commerce_update_checks enable row level security;

revoke all on table public.commerce_categories from anon, authenticated;
revoke all on table public.commerce_subcategories from anon, authenticated;
revoke all on table public.commerce_products from anon, authenticated;
revoke all on table public.commerce_product_skus from anon, authenticated;
revoke all on table public.commerce_marketplaces from anon, authenticated;
revoke all on table public.commerce_listings from anon, authenticated;
revoke all on table public.commerce_listing_products from anon, authenticated;
revoke all on table public.commerce_import_batches from anon, authenticated;
revoke all on table public.commerce_import_rows from anon, authenticated;
revoke all on table public.commerce_reconciliation_candidates from anon, authenticated;
revoke all on table public.commerce_update_campaigns from anon, authenticated;
revoke all on table public.commerce_update_items from anon, authenticated;
revoke all on table public.commerce_update_checks from anon, authenticated;

revoke all on function public.commerce_touch_updated_at() from public, anon, authenticated;
grant execute on function public.commerce_touch_updated_at() to service_role;

grant select, insert, update, delete on table public.commerce_categories to service_role;
grant select, insert, update, delete on table public.commerce_subcategories to service_role;
grant select, insert, update, delete on table public.commerce_products to service_role;
grant select, insert, update, delete on table public.commerce_product_skus to service_role;
grant select, insert, update, delete on table public.commerce_marketplaces to service_role;
grant select, insert, update, delete on table public.commerce_listings to service_role;
grant select, insert, update, delete on table public.commerce_listing_products to service_role;
grant select, insert, update, delete on table public.commerce_import_batches to service_role;
grant select, insert, update, delete on table public.commerce_import_rows to service_role;
grant select, insert, update, delete on table public.commerce_reconciliation_candidates to service_role;
grant select, insert, update, delete on table public.commerce_update_campaigns to service_role;
grant select, insert, update, delete on table public.commerce_update_items to service_role;
grant select, insert, update, delete on table public.commerce_update_checks to service_role;

grant usage, select on all sequences in schema public to service_role;

commit;
