begin;

create table if not exists public.commerce_product_media_links (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.commerce_products(id) on delete cascade,
  source_kind text not null default 'NISTI_ID',
  source_product_id bigint references public.products(id) on delete set null,
  matched_sku text not null,
  image_key text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint commerce_product_media_links_source_kind_ck
    check (source_kind in ('NISTI_ID')),
  constraint commerce_product_media_links_product_source_uq
    unique (product_id, source_kind)
);

create index if not exists commerce_product_media_links_source_product_idx
  on public.commerce_product_media_links(source_product_id);

create table if not exists public.commerce_preview_product_media_links (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.commerce_preview_products(id) on delete cascade,
  source_kind text not null default 'NISTI_ID',
  source_product_id bigint references public.products(id) on delete set null,
  matched_sku text not null,
  image_key text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint commerce_preview_product_media_links_source_kind_ck
    check (source_kind in ('NISTI_ID')),
  constraint commerce_preview_product_media_links_product_source_uq
    unique (product_id, source_kind)
);

create index if not exists commerce_preview_product_media_links_source_product_idx
  on public.commerce_preview_product_media_links(source_product_id);

insert into public.commerce_product_media_links(
  product_id,source_kind,source_product_id,matched_sku,image_key,updated_at
)
select
  cp.id,
  'NISTI_ID',
  core.id,
  cps.sku,
  core.image_key,
  now()
from public.commerce_products cp
join public.commerce_product_skus cps
  on cps.product_id=cp.id
 and cps.sku_type='CURRENT'
 and cps.is_active=true
join public.products core
  on upper(btrim(core.sku))=upper(btrim(cps.sku))
 and nullif(btrim(coalesce(core.image_key,'')),'') is not null
on conflict (product_id,source_kind)
do update set
  source_product_id=excluded.source_product_id,
  matched_sku=excluded.matched_sku,
  image_key=excluded.image_key,
  updated_at=now();

insert into public.commerce_preview_product_media_links(
  product_id,source_kind,source_product_id,matched_sku,image_key,updated_at
)
select
  cp.id,
  'NISTI_ID',
  core.id,
  cps.sku,
  core.image_key,
  now()
from public.commerce_preview_products cp
join public.commerce_preview_product_skus cps
  on cps.product_id=cp.id
 and cps.sku_type='CURRENT'
 and cps.is_active=true
join public.products core
  on upper(btrim(core.sku))=upper(btrim(cps.sku))
 and nullif(btrim(coalesce(core.image_key,'')),'') is not null
on conflict (product_id,source_kind)
do update set
  source_product_id=excluded.source_product_id,
  matched_sku=excluded.matched_sku,
  image_key=excluded.image_key,
  updated_at=now();

create or replace function public.commerce_list_products_v3(
  p_search text default null,
  p_marketplace_code text default null,
  p_category_id bigint default null,
  p_internal_status text default null,
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  product_id bigint,
  name text,
  current_sku text,
  category_id bigint,
  category_name text,
  subcategory_id bigint,
  subcategory_name text,
  temporal_type text,
  edition_year integer,
  internal_status text,
  marketplace_count bigint,
  listing_count bigint,
  marketplace_codes text[],
  total_count bigint,
  thumbnail_url text,
  thumbnail_listing_id bigint,
  thumbnail_source text
)
language sql
stable
security invoker
set search_path=public
as $$
  select
    p.product_id,p.name,p.current_sku,p.category_id,p.category_name,
    p.subcategory_id,p.subcategory_name,p.temporal_type,p.edition_year,
    p.internal_status,p.marketplace_count,p.listing_count,p.marketplace_codes,p.total_count,
    coalesce(
      p.thumbnail_url,
      case when media.source_product_id is not null then '/api/images/' || media.source_product_id::text end
    ) as thumbnail_url,
    p.thumbnail_listing_id,
    case
      when p.thumbnail_url is not null then 'MARKETPLACE'
      when media.source_product_id is not null then 'NISTI_ID'
      else null
    end as thumbnail_source
  from public.commerce_list_products_v2(
    p_search,p_marketplace_code,p_category_id,p_internal_status,p_limit,p_offset
  ) p
  left join public.commerce_product_media_links media
    on media.product_id=p.product_id
   and media.source_kind='NISTI_ID';
$$;

create or replace function public.commerce_preview_list_products_v3(
  p_search text default null,
  p_marketplace_code text default null,
  p_category_id bigint default null,
  p_internal_status text default null,
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  product_id bigint,
  name text,
  current_sku text,
  category_id bigint,
  category_name text,
  subcategory_id bigint,
  subcategory_name text,
  temporal_type text,
  edition_year integer,
  internal_status text,
  marketplace_count bigint,
  listing_count bigint,
  marketplace_codes text[],
  total_count bigint,
  thumbnail_url text,
  thumbnail_listing_id bigint,
  thumbnail_source text
)
language sql
stable
security invoker
set search_path=public
as $$
  select
    p.product_id,p.name,p.current_sku,p.category_id,p.category_name,
    p.subcategory_id,p.subcategory_name,p.temporal_type,p.edition_year,
    p.internal_status,p.marketplace_count,p.listing_count,p.marketplace_codes,p.total_count,
    coalesce(
      p.thumbnail_url,
      case when media.source_product_id is not null then '/api/images/' || media.source_product_id::text end
    ) as thumbnail_url,
    p.thumbnail_listing_id,
    case
      when p.thumbnail_url is not null then 'MARKETPLACE'
      when media.source_product_id is not null then 'NISTI_ID'
      else null
    end as thumbnail_source
  from public.commerce_preview_list_products_v2(
    p_search,p_marketplace_code,p_category_id,p_internal_status,p_limit,p_offset
  ) p
  left join public.commerce_preview_product_media_links media
    on media.product_id=p.product_id
   and media.source_kind='NISTI_ID';
$$;

create or replace function public.commerce_list_listings_v3(
  p_search text default null,
  p_marketplace_code text default null,
  p_listing_status text default null,
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  listing_id bigint,
  marketplace_code text,
  marketplace_name text,
  external_listing_id text,
  canonical_url text,
  title text,
  listing_status text,
  sales_status text,
  video_status text,
  observed_year integer,
  product_count bigint,
  platform_skus text[],
  last_checked_at timestamptz,
  total_count bigint,
  cover_image_url text,
  product_image_urls jsonb,
  variation_name text,
  variation_options jsonb,
  marketplace_category text,
  snapshot_key text,
  cover_image_source text,
  fallback_product_images jsonb
)
language sql
stable
security invoker
set search_path=public
as $$
  select
    l.listing_id,l.marketplace_code,l.marketplace_name,l.external_listing_id,l.canonical_url,l.title,
    l.listing_status,l.sales_status,l.video_status,l.observed_year,l.product_count,l.platform_skus,
    l.last_checked_at,l.total_count,
    coalesce(
      l.cover_image_url,
      fallback.images->0->>'image_url'
    ) as cover_image_url,
    l.product_image_urls,l.variation_name,l.variation_options,l.marketplace_category,l.snapshot_key,
    case
      when l.cover_image_url is not null then 'MARKETPLACE'
      when jsonb_array_length(coalesce(fallback.images,'[]'::jsonb)) > 0 then 'NISTI_ID'
      else null
    end as cover_image_source,
    coalesce(fallback.images,'[]'::jsonb) as fallback_product_images
  from public.commerce_list_listings_v2(
    p_search,p_marketplace_code,p_listing_status,p_limit,p_offset
  ) l
  left join lateral (
    select jsonb_agg(
      jsonb_build_object(
        'product_id',x.product_id,
        'sku',x.sku,
        'variation_name',x.variation_name,
        'source_product_id',x.source_product_id,
        'image_url','/api/images/' || x.source_product_id::text
      )
      order by x.product_id
    ) as images
    from (
      select distinct
        lp.product_id,
        cps.sku,
        lp.variation_name,
        media.source_product_id
      from public.commerce_listing_products lp
      join public.commerce_product_skus cps
        on cps.product_id=lp.product_id
       and cps.sku_type='CURRENT'
       and cps.is_active=true
      join public.commerce_product_media_links media
        on media.product_id=lp.product_id
       and media.source_kind='NISTI_ID'
       and media.source_product_id is not null
      where lp.listing_id=l.listing_id
        and lp.relation_status<>'REMOVED'
    ) x
  ) fallback on true;
$$;

create or replace function public.commerce_preview_list_listings_v3(
  p_search text default null,
  p_marketplace_code text default null,
  p_listing_status text default null,
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  listing_id bigint,
  marketplace_code text,
  marketplace_name text,
  external_listing_id text,
  canonical_url text,
  title text,
  listing_status text,
  sales_status text,
  video_status text,
  observed_year integer,
  product_count bigint,
  platform_skus text[],
  last_checked_at timestamptz,
  total_count bigint,
  cover_image_url text,
  product_image_urls jsonb,
  variation_name text,
  variation_options jsonb,
  marketplace_category text,
  snapshot_key text,
  cover_image_source text,
  fallback_product_images jsonb
)
language sql
stable
security invoker
set search_path=public
as $$
  select
    l.listing_id,l.marketplace_code,l.marketplace_name,l.external_listing_id,l.canonical_url,l.title,
    l.listing_status,l.sales_status,l.video_status,l.observed_year,l.product_count,l.platform_skus,
    l.last_checked_at,l.total_count,
    coalesce(
      l.cover_image_url,
      fallback.images->0->>'image_url'
    ) as cover_image_url,
    l.product_image_urls,l.variation_name,l.variation_options,l.marketplace_category,l.snapshot_key,
    case
      when l.cover_image_url is not null then 'MARKETPLACE'
      when jsonb_array_length(coalesce(fallback.images,'[]'::jsonb)) > 0 then 'NISTI_ID'
      else null
    end as cover_image_source,
    coalesce(fallback.images,'[]'::jsonb) as fallback_product_images
  from public.commerce_preview_list_listings_v2(
    p_search,p_marketplace_code,p_listing_status,p_limit,p_offset
  ) l
  left join lateral (
    select jsonb_agg(
      jsonb_build_object(
        'product_id',x.product_id,
        'sku',x.sku,
        'variation_name',x.variation_name,
        'source_product_id',x.source_product_id,
        'image_url','/api/images/' || x.source_product_id::text
      )
      order by x.product_id
    ) as images
    from (
      select distinct
        lp.product_id,
        cps.sku,
        lp.variation_name,
        media.source_product_id
      from public.commerce_preview_listing_products lp
      join public.commerce_preview_product_skus cps
        on cps.product_id=lp.product_id
       and cps.sku_type='CURRENT'
       and cps.is_active=true
      join public.commerce_preview_product_media_links media
        on media.product_id=lp.product_id
       and media.source_kind='NISTI_ID'
       and media.source_product_id is not null
      where lp.listing_id=l.listing_id
        and lp.relation_status<>'REMOVED'
    ) x
  ) fallback on true;
$$;

revoke all on table public.commerce_product_media_links from public,anon,authenticated;
revoke all on table public.commerce_preview_product_media_links from public,anon,authenticated;
grant select,insert,update on table public.commerce_product_media_links to service_role;
grant select,insert,update on table public.commerce_preview_product_media_links to service_role;
grant usage,select on sequence public.commerce_product_media_links_id_seq to service_role;
grant usage,select on sequence public.commerce_preview_product_media_links_id_seq to service_role;

revoke all on function public.commerce_list_products_v3(text,text,bigint,text,integer,integer)
  from public,anon,authenticated;
revoke all on function public.commerce_preview_list_products_v3(text,text,bigint,text,integer,integer)
  from public,anon,authenticated;
revoke all on function public.commerce_list_listings_v3(text,text,text,integer,integer)
  from public,anon,authenticated;
revoke all on function public.commerce_preview_list_listings_v3(text,text,text,integer,integer)
  from public,anon,authenticated;

grant execute on function public.commerce_list_products_v3(text,text,bigint,text,integer,integer)
  to service_role;
grant execute on function public.commerce_preview_list_products_v3(text,text,bigint,text,integer,integer)
  to service_role;
grant execute on function public.commerce_list_listings_v3(text,text,text,integer,integer)
  to service_role;
grant execute on function public.commerce_preview_list_listings_v3(text,text,text,integer,integer)
  to service_role;

commit;
