
create table if not exists public.commerce_listing_overrides (
  listing_id bigint primary key references public.commerce_listings(id) on delete cascade,
  title text,
  listing_status text,
  observed_year integer,
  image_url text,
  price text,
  category text,
  note text,
  sync_status text not null default 'LOCAL',
  updated_by text,
  updated_at timestamptz not null default now(),
  constraint commerce_listing_overrides_status_chk
    check (listing_status is null or listing_status in ('UNKNOWN','ACTIVE','PAUSED','INACTIVE','REMOVED')),
  constraint commerce_listing_overrides_sync_chk
    check (sync_status in ('LOCAL','PENDING','SYNCED','FAILED'))
);

alter table public.commerce_listing_overrides enable row level security;
revoke all on table public.commerce_listing_overrides from public, anon, authenticated;
grant select, insert, update, delete on table public.commerce_listing_overrides to service_role;

create table if not exists public.commerce_listing_edit_history (
  id bigint generated by default as identity primary key,
  batch_token uuid not null default gen_random_uuid(),
  listing_id bigint not null references public.commerce_listings(id) on delete cascade,
  field_name text not null,
  old_value jsonb not null default '{}'::jsonb,
  new_value jsonb not null default '{}'::jsonb,
  operator_name text,
  created_at timestamptz not null default now()
);

create index if not exists commerce_listing_edit_history_listing_idx
  on public.commerce_listing_edit_history(listing_id, created_at desc);
create index if not exists commerce_listing_edit_history_batch_idx
  on public.commerce_listing_edit_history(batch_token);

alter table public.commerce_listing_edit_history enable row level security;
revoke all on table public.commerce_listing_edit_history from public, anon, authenticated;
grant select, insert on table public.commerce_listing_edit_history to service_role;
grant usage, select on sequence public.commerce_listing_edit_history_id_seq to service_role;

create table if not exists public.commerce_preview_listing_overrides (
  listing_id bigint primary key references public.commerce_preview_listings(id) on delete cascade,
  title text,
  listing_status text,
  observed_year integer,
  image_url text,
  price text,
  category text,
  note text,
  sync_status text not null default 'LOCAL',
  updated_by text,
  updated_at timestamptz not null default now(),
  constraint commerce_preview_listing_overrides_status_chk
    check (listing_status is null or listing_status in ('UNKNOWN','ACTIVE','PAUSED','INACTIVE','REMOVED')),
  constraint commerce_preview_listing_overrides_sync_chk
    check (sync_status in ('LOCAL','PENDING','SYNCED','FAILED'))
);

alter table public.commerce_preview_listing_overrides enable row level security;
revoke all on table public.commerce_preview_listing_overrides from public, anon, authenticated;
grant select, insert, update, delete on table public.commerce_preview_listing_overrides to service_role;

create table if not exists public.commerce_preview_listing_edit_history (
  id bigint generated by default as identity primary key,
  batch_token uuid not null default gen_random_uuid(),
  listing_id bigint not null references public.commerce_preview_listings(id) on delete cascade,
  field_name text not null,
  old_value jsonb not null default '{}'::jsonb,
  new_value jsonb not null default '{}'::jsonb,
  operator_name text,
  created_at timestamptz not null default now()
);

create index if not exists commerce_preview_listing_edit_history_listing_idx
  on public.commerce_preview_listing_edit_history(listing_id, created_at desc);
create index if not exists commerce_preview_listing_edit_history_batch_idx
  on public.commerce_preview_listing_edit_history(batch_token);

alter table public.commerce_preview_listing_edit_history enable row level security;
revoke all on table public.commerce_preview_listing_edit_history from public, anon, authenticated;
grant select, insert on table public.commerce_preview_listing_edit_history to service_role;
grant usage, select on sequence public.commerce_preview_listing_edit_history_id_seq to service_role;

create or replace function public.commerce_edit_listing_v1(
  p_listing_id bigint,
  p_patch jsonb,
  p_operator text default null,
  p_batch_token uuid default null
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_title text;
  v_status text;
  v_year integer;
  v_image text;
  v_price text;
  v_category text;
  v_note text;
  v_sync text;
  v_before jsonb;
  v_after jsonb;
  v_batch uuid := coalesce(p_batch_token, gen_random_uuid());
  v_fields text;
begin
  if p_listing_id is null or p_listing_id <= 0 then
    raise exception 'listing_id_invalid' using errcode='22023';
  end if;
  if p_patch is null or jsonb_typeof(p_patch) <> 'object' then
    raise exception 'patch_invalid' using errcode='22023';
  end if;
  if exists (
    select 1
    from jsonb_object_keys(p_patch) k(key)
    where k.key not in ('title','listing_status','observed_year','image_url','price','category','note')
  ) then
    raise exception 'patch_field_invalid' using errcode='22023';
  end if;

  select
    coalesce(o.title,l.title),
    coalesce(o.listing_status,l.listing_status),
    coalesce(o.observed_year,l.observed_year),
    o.image_url,
    o.price,
    o.category,
    o.note,
    coalesce(o.sync_status,'LOCAL')
  into v_title,v_status,v_year,v_image,v_price,v_category,v_note,v_sync
  from public.commerce_listings l
  left join public.commerce_listing_overrides o on o.listing_id=l.id
  where l.id=p_listing_id;

  if not found then
    raise exception 'listing_not_found' using errcode='22023';
  end if;

  v_before := jsonb_build_object(
    'title',v_title,'listing_status',v_status,'observed_year',v_year,
    'image_url',v_image,'price',v_price,'category',v_category,'note',v_note,
    'sync_status',v_sync
  );

  if p_patch ? 'title' then v_title := nullif(btrim(p_patch->>'title'),''); end if;
  if p_patch ? 'listing_status' then v_status := nullif(upper(btrim(p_patch->>'listing_status')),''); end if;
  if p_patch ? 'observed_year' then
    v_year := case when nullif(btrim(p_patch->>'observed_year'),'') is null then null else (p_patch->>'observed_year')::integer end;
  end if;
  if p_patch ? 'image_url' then v_image := nullif(btrim(p_patch->>'image_url'),''); end if;
  if p_patch ? 'price' then v_price := nullif(btrim(p_patch->>'price'),''); end if;
  if p_patch ? 'category' then v_category := nullif(btrim(p_patch->>'category'),''); end if;
  if p_patch ? 'note' then v_note := nullif(btrim(p_patch->>'note'),''); end if;

  if v_status is not null and v_status not in ('UNKNOWN','ACTIVE','PAUSED','INACTIVE','REMOVED') then
    raise exception 'listing_status_invalid' using errcode='22023';
  end if;
  if v_year is not null and (v_year < 2000 or v_year > 2100) then
    raise exception 'observed_year_invalid' using errcode='22023';
  end if;

  insert into public.commerce_listing_overrides(
    listing_id,title,listing_status,observed_year,image_url,price,category,note,sync_status,updated_by,updated_at
  ) values (
    p_listing_id,v_title,v_status,v_year,v_image,v_price,v_category,v_note,'LOCAL',
    nullif(btrim(coalesce(p_operator,'')),''),now()
  )
  on conflict (listing_id) do update set
    title=excluded.title,
    listing_status=excluded.listing_status,
    observed_year=excluded.observed_year,
    image_url=excluded.image_url,
    price=excluded.price,
    category=excluded.category,
    note=excluded.note,
    sync_status='LOCAL',
    updated_by=excluded.updated_by,
    updated_at=now();

  v_after := jsonb_build_object(
    'title',v_title,'listing_status',v_status,'observed_year',v_year,
    'image_url',v_image,'price',v_price,'category',v_category,'note',v_note,
    'sync_status','LOCAL'
  );

  select string_agg(key,',' order by key) into v_fields
  from jsonb_object_keys(p_patch) k(key);

  insert into public.commerce_listing_edit_history(
    batch_token,listing_id,field_name,old_value,new_value,operator_name
  ) values (
    v_batch,p_listing_id,coalesce(v_fields,'PATCH'),v_before,v_after,
    nullif(btrim(coalesce(p_operator,'')),'')
  );

  return v_after || jsonb_build_object('listing_id',p_listing_id,'batch_token',v_batch);
end;
$$;

create or replace function public.commerce_bulk_edit_listings_v1(
  p_listing_ids bigint[],
  p_action text,
  p_value text,
  p_operator text default null
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_id bigint;
  v_action text := upper(btrim(coalesce(p_action,'')));
  v_patch jsonb;
  v_current_title text;
  v_batch uuid := gen_random_uuid();
  v_changed integer := 0;
begin
  if p_listing_ids is null or coalesce(array_length(p_listing_ids,1),0)=0 then
    raise exception 'listing_ids_required' using errcode='22023';
  end if;
  if v_action not in ('LISTING_STATUS','TITLE','OBSERVED_YEAR','IMAGE_URL','PRICE','CATEGORY','NOTE','TITLE_ADD','TITLE_REMOVE') then
    raise exception 'bulk_action_invalid' using errcode='22023';
  end if;

  for v_id in select distinct x from unnest(p_listing_ids) x where x is not null and x > 0 loop
    if v_action='TITLE_ADD' or v_action='TITLE_REMOVE' then
      select coalesce(o.title,l.title,'')
      into v_current_title
      from public.commerce_listings l
      left join public.commerce_listing_overrides o on o.listing_id=l.id
      where l.id=v_id;

      if not found then
        raise exception 'listing_not_found' using errcode='22023';
      end if;

      if v_action='TITLE_ADD' then
        v_patch := jsonb_build_object('title',btrim(concat_ws(' ',v_current_title,nullif(btrim(coalesce(p_value,'')),''))));
      else
        v_patch := jsonb_build_object('title',btrim(replace(v_current_title,coalesce(p_value,''),'')));
      end if;
    elsif v_action='LISTING_STATUS' then
      v_patch := jsonb_build_object('listing_status',p_value);
    elsif v_action='TITLE' then
      v_patch := jsonb_build_object('title',p_value);
    elsif v_action='OBSERVED_YEAR' then
      v_patch := jsonb_build_object('observed_year',p_value);
    elsif v_action='IMAGE_URL' then
      v_patch := jsonb_build_object('image_url',p_value);
    elsif v_action='PRICE' then
      v_patch := jsonb_build_object('price',p_value);
    elsif v_action='CATEGORY' then
      v_patch := jsonb_build_object('category',p_value);
    else
      v_patch := jsonb_build_object('note',p_value);
    end if;

    perform public.commerce_edit_listing_v1(v_id,v_patch,p_operator,v_batch);
    v_changed := v_changed + 1;
  end loop;

  return jsonb_build_object(
    'batch_token',v_batch,
    'requested_count',coalesce(array_length(p_listing_ids,1),0),
    'changed_count',v_changed,
    'action',v_action
  );
end;
$$;

create or replace function public.commerce_queue_listing_sync_v1(
  p_listing_id bigint,
  p_operator text default null
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_batch uuid := gen_random_uuid();
  v_before text;
begin
  if not exists (select 1 from public.commerce_listings where id=p_listing_id) then
    raise exception 'listing_not_found' using errcode='22023';
  end if;

  select coalesce(sync_status,'NONE') into v_before
  from public.commerce_listing_overrides
  where listing_id=p_listing_id;

  insert into public.commerce_listing_overrides(listing_id,sync_status,updated_by,updated_at)
  values(p_listing_id,'PENDING',nullif(btrim(coalesce(p_operator,'')),''),now())
  on conflict(listing_id) do update set
    sync_status='PENDING',
    updated_by=excluded.updated_by,
    updated_at=now();

  insert into public.commerce_listing_edit_history(
    batch_token,listing_id,field_name,old_value,new_value,operator_name
  ) values(
    v_batch,p_listing_id,'SYNC_STATUS',
    jsonb_build_object('sync_status',coalesce(v_before,'NONE')),
    jsonb_build_object('sync_status','PENDING'),
    nullif(btrim(coalesce(p_operator,'')),'')
  );

  return jsonb_build_object('listing_id',p_listing_id,'sync_status','PENDING','batch_token',v_batch);
end;
$$;

create or replace function public.commerce_listing_editor_v1(p_listing_id bigint)
returns jsonb
language sql
stable
security invoker
set search_path = public
as $$
select jsonb_build_object(
  'listing_id',l.id,
  'marketplace_code',m.code,
  'marketplace_name',m.name,
  'external_listing_id',l.external_listing_id,
  'canonical_url',l.canonical_url,
  'base_title',l.title,
  'title',coalesce(o.title,l.title),
  'base_listing_status',l.listing_status,
  'listing_status',coalesce(o.listing_status,l.listing_status),
  'base_observed_year',l.observed_year,
  'observed_year',coalesce(o.observed_year,l.observed_year),
  'image_url',coalesce(
    o.image_url,
    (
      select nullif(sr.normalized_payload->>'image_url','')
      from public.commerce_source_rows sr
      where sr.matched_listing_id=l.id
        and sr.is_header=false
        and nullif(sr.normalized_payload->>'image_url','') is not null
      order by sr.imported_at desc nulls last,sr.id desc
      limit 1
    )
  ),
  'price',coalesce(o.price,nullif(l.raw_metadata->>'price',''),nullif(l.raw_metadata->>'sale_price','')),
  'category',coalesce(o.category,nullif(l.raw_metadata->>'marketplace_category',''),nullif(l.raw_metadata->>'category','')),
  'note',o.note,
  'sync_status',coalesce(o.sync_status,'NONE'),
  'updated_by',o.updated_by,
  'updated_at',o.updated_at,
  'platform_skus',coalesce((
    select jsonb_agg(distinct coalesce(nullif(lp.platform_sku,''),ps.sku)) filter (where coalesce(nullif(lp.platform_sku,''),ps.sku) is not null)
    from public.commerce_listing_products lp
    left join public.commerce_product_skus ps on ps.id=lp.product_sku_id
    where lp.listing_id=l.id
  ),'[]'::jsonb),
  'products',coalesce((
    select jsonb_agg(jsonb_build_object(
      'product_id',p.id,'name',p.name,'platform_sku',lp.platform_sku,'variation_name',lp.variation_name
    ) order by p.name,p.id)
    from public.commerce_listing_products lp
    join public.commerce_products p on p.id=lp.product_id
    where lp.listing_id=l.id
  ),'[]'::jsonb),
  'history',coalesce((
    select jsonb_agg(jsonb_build_object(
      'id',h.id,'batch_token',h.batch_token,'field_name',h.field_name,
      'old_value',h.old_value,'new_value',h.new_value,
      'operator_name',h.operator_name,'created_at',h.created_at
    ) order by h.created_at desc,h.id desc)
    from (
      select *
      from public.commerce_listing_edit_history
      where listing_id=l.id
      order by created_at desc,id desc
      limit 20
    ) h
  ),'[]'::jsonb)
)
from public.commerce_listings l
join public.commerce_marketplaces m on m.id=l.marketplace_id
left join public.commerce_listing_overrides o on o.listing_id=l.id
where l.id=p_listing_id;
$$;

create or replace function public.commerce_enrich_management_platforms_v1(p_platforms jsonb)
returns jsonb
language sql
stable
security invoker
set search_path = public
as $$
select coalesce(jsonb_agg(
  p.platform || jsonb_build_object('items',coalesce(e.items,'[]'::jsonb))
  order by p.ord
),'[]'::jsonb)
from jsonb_array_elements(coalesce(p_platforms,'[]'::jsonb)) with ordinality p(platform,ord)
left join lateral (
  select jsonb_agg(
    i.item || jsonb_build_object(
      'listing_id',l.id,
      'listing_title',coalesce(o.title,l.title,i.item->>'product_name'),
      'listing_status',coalesce(o.listing_status,i.item->>'listing_status'),
      'edition_year',coalesce(o.observed_year,case when (i.item->>'edition_year') ~ '^[0-9]+$' then (i.item->>'edition_year')::integer end),
      'image_url',coalesce(o.image_url,nullif(i.item->>'image_url','')),
      'price',o.price,
      'listing_category',o.category,
      'listing_note',o.note,
      'sync_status',coalesce(o.sync_status,'NONE')
    )
    order by i.iord
  ) as items
  from jsonb_array_elements(coalesce(p.platform->'items','[]'::jsonb)) with ordinality i(item,iord)
  left join public.commerce_source_rows sr
    on sr.id=case when (i.item->>'source_row_id') ~ '^[0-9]+$' then (i.item->>'source_row_id')::bigint end
  left join public.commerce_listings l on l.id=sr.matched_listing_id
  left join public.commerce_listing_overrides o on o.listing_id=l.id
) e on true;
$$;

create or replace function public.commerce_management_products_v3(
  p_search text default null,
  p_category text default null,
  p_year integer default null,
  p_presence text default 'LINKED',
  p_limit integer default 24,
  p_offset integer default 0
)
returns table(
  card_key text,
  product_id bigint,
  product_name text,
  master_sku text,
  category_name text,
  edition_year integer,
  image_url text,
  platform_count integer,
  presence_type text,
  platforms jsonb,
  link_review_status text,
  suggested_product_id bigint,
  candidate_count integer,
  total_count bigint
)
language sql
stable
security invoker
set search_path = public
as $$
select
  b.card_key,b.product_id,b.product_name,b.master_sku,b.category_name,b.edition_year,b.image_url,
  b.platform_count,b.presence_type,
  public.commerce_enrich_management_platforms_v1(b.platforms) as platforms,
  b.link_review_status,b.suggested_product_id,b.candidate_count,b.total_count
from public.commerce_management_products_v2(p_search,p_category,p_year,p_presence,p_limit,p_offset) b;
$$;

create or replace function public.commerce_preview_edit_listing_v1(
  p_listing_id bigint,
  p_patch jsonb,
  p_operator text default null,
  p_batch_token uuid default null
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_title text;
  v_status text;
  v_year integer;
  v_image text;
  v_price text;
  v_category text;
  v_note text;
  v_sync text;
  v_before jsonb;
  v_after jsonb;
  v_batch uuid := coalesce(p_batch_token, gen_random_uuid());
  v_fields text;
begin
  if p_listing_id is null or p_listing_id <= 0 then
    raise exception 'listing_id_invalid' using errcode='22023';
  end if;
  if p_patch is null or jsonb_typeof(p_patch) <> 'object' then
    raise exception 'patch_invalid' using errcode='22023';
  end if;
  if exists (
    select 1 from jsonb_object_keys(p_patch) k(key)
    where k.key not in ('title','listing_status','observed_year','image_url','price','category','note')
  ) then
    raise exception 'patch_field_invalid' using errcode='22023';
  end if;

  select
    coalesce(o.title,l.title),
    coalesce(o.listing_status,l.listing_status),
    coalesce(o.observed_year,l.observed_year),
    o.image_url,o.price,o.category,o.note,coalesce(o.sync_status,'LOCAL')
  into v_title,v_status,v_year,v_image,v_price,v_category,v_note,v_sync
  from public.commerce_preview_listings l
  left join public.commerce_preview_listing_overrides o on o.listing_id=l.id
  where l.id=p_listing_id;

  if not found then raise exception 'listing_not_found' using errcode='22023'; end if;

  v_before := jsonb_build_object(
    'title',v_title,'listing_status',v_status,'observed_year',v_year,
    'image_url',v_image,'price',v_price,'category',v_category,'note',v_note,'sync_status',v_sync
  );

  if p_patch ? 'title' then v_title := nullif(btrim(p_patch->>'title'),''); end if;
  if p_patch ? 'listing_status' then v_status := nullif(upper(btrim(p_patch->>'listing_status')),''); end if;
  if p_patch ? 'observed_year' then
    v_year := case when nullif(btrim(p_patch->>'observed_year'),'') is null then null else (p_patch->>'observed_year')::integer end;
  end if;
  if p_patch ? 'image_url' then v_image := nullif(btrim(p_patch->>'image_url'),''); end if;
  if p_patch ? 'price' then v_price := nullif(btrim(p_patch->>'price'),''); end if;
  if p_patch ? 'category' then v_category := nullif(btrim(p_patch->>'category'),''); end if;
  if p_patch ? 'note' then v_note := nullif(btrim(p_patch->>'note'),''); end if;

  if v_status is not null and v_status not in ('UNKNOWN','ACTIVE','PAUSED','INACTIVE','REMOVED') then
    raise exception 'listing_status_invalid' using errcode='22023';
  end if;
  if v_year is not null and (v_year < 2000 or v_year > 2100) then
    raise exception 'observed_year_invalid' using errcode='22023';
  end if;

  insert into public.commerce_preview_listing_overrides(
    listing_id,title,listing_status,observed_year,image_url,price,category,note,sync_status,updated_by,updated_at
  ) values(
    p_listing_id,v_title,v_status,v_year,v_image,v_price,v_category,v_note,'LOCAL',
    nullif(btrim(coalesce(p_operator,'')),''),now()
  )
  on conflict(listing_id) do update set
    title=excluded.title,listing_status=excluded.listing_status,observed_year=excluded.observed_year,
    image_url=excluded.image_url,price=excluded.price,category=excluded.category,note=excluded.note,
    sync_status='LOCAL',updated_by=excluded.updated_by,updated_at=now();

  v_after := jsonb_build_object(
    'title',v_title,'listing_status',v_status,'observed_year',v_year,
    'image_url',v_image,'price',v_price,'category',v_category,'note',v_note,'sync_status','LOCAL'
  );

  select string_agg(key,',' order by key) into v_fields
  from jsonb_object_keys(p_patch) k(key);

  insert into public.commerce_preview_listing_edit_history(
    batch_token,listing_id,field_name,old_value,new_value,operator_name
  ) values(
    v_batch,p_listing_id,coalesce(v_fields,'PATCH'),v_before,v_after,
    nullif(btrim(coalesce(p_operator,'')),'')
  );

  return v_after || jsonb_build_object('listing_id',p_listing_id,'batch_token',v_batch);
end;
$$;

create or replace function public.commerce_preview_bulk_edit_listings_v1(
  p_listing_ids bigint[],
  p_action text,
  p_value text,
  p_operator text default null
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_id bigint;
  v_action text := upper(btrim(coalesce(p_action,'')));
  v_patch jsonb;
  v_current_title text;
  v_batch uuid := gen_random_uuid();
  v_changed integer := 0;
begin
  if p_listing_ids is null or coalesce(array_length(p_listing_ids,1),0)=0 then
    raise exception 'listing_ids_required' using errcode='22023';
  end if;
  if v_action not in ('LISTING_STATUS','TITLE','OBSERVED_YEAR','IMAGE_URL','PRICE','CATEGORY','NOTE','TITLE_ADD','TITLE_REMOVE') then
    raise exception 'bulk_action_invalid' using errcode='22023';
  end if;

  for v_id in select distinct x from unnest(p_listing_ids) x where x is not null and x > 0 loop
    if v_action='TITLE_ADD' or v_action='TITLE_REMOVE' then
      select coalesce(o.title,l.title,'')
      into v_current_title
      from public.commerce_preview_listings l
      left join public.commerce_preview_listing_overrides o on o.listing_id=l.id
      where l.id=v_id;
      if not found then raise exception 'listing_not_found' using errcode='22023'; end if;
      if v_action='TITLE_ADD' then
        v_patch := jsonb_build_object('title',btrim(concat_ws(' ',v_current_title,nullif(btrim(coalesce(p_value,'')),''))));
      else
        v_patch := jsonb_build_object('title',btrim(replace(v_current_title,coalesce(p_value,''),'')));
      end if;
    elsif v_action='LISTING_STATUS' then v_patch := jsonb_build_object('listing_status',p_value);
    elsif v_action='TITLE' then v_patch := jsonb_build_object('title',p_value);
    elsif v_action='OBSERVED_YEAR' then v_patch := jsonb_build_object('observed_year',p_value);
    elsif v_action='IMAGE_URL' then v_patch := jsonb_build_object('image_url',p_value);
    elsif v_action='PRICE' then v_patch := jsonb_build_object('price',p_value);
    elsif v_action='CATEGORY' then v_patch := jsonb_build_object('category',p_value);
    else v_patch := jsonb_build_object('note',p_value);
    end if;
    perform public.commerce_preview_edit_listing_v1(v_id,v_patch,p_operator,v_batch);
    v_changed := v_changed + 1;
  end loop;

  return jsonb_build_object(
    'batch_token',v_batch,'requested_count',coalesce(array_length(p_listing_ids,1),0),
    'changed_count',v_changed,'action',v_action
  );
end;
$$;

create or replace function public.commerce_preview_queue_listing_sync_v1(
  p_listing_id bigint,
  p_operator text default null
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_batch uuid := gen_random_uuid();
  v_before text;
begin
  if not exists (select 1 from public.commerce_preview_listings where id=p_listing_id) then
    raise exception 'listing_not_found' using errcode='22023';
  end if;

  select coalesce(sync_status,'NONE') into v_before
  from public.commerce_preview_listing_overrides where listing_id=p_listing_id;

  insert into public.commerce_preview_listing_overrides(listing_id,sync_status,updated_by,updated_at)
  values(p_listing_id,'PENDING',nullif(btrim(coalesce(p_operator,'')),''),now())
  on conflict(listing_id) do update set
    sync_status='PENDING',updated_by=excluded.updated_by,updated_at=now();

  insert into public.commerce_preview_listing_edit_history(
    batch_token,listing_id,field_name,old_value,new_value,operator_name
  ) values(
    v_batch,p_listing_id,'SYNC_STATUS',
    jsonb_build_object('sync_status',coalesce(v_before,'NONE')),
    jsonb_build_object('sync_status','PENDING'),
    nullif(btrim(coalesce(p_operator,'')),'')
  );

  return jsonb_build_object('listing_id',p_listing_id,'sync_status','PENDING','batch_token',v_batch);
end;
$$;

create or replace function public.commerce_preview_listing_editor_v1(p_listing_id bigint)
returns jsonb
language sql
stable
security invoker
set search_path = public
as $$
select jsonb_build_object(
  'listing_id',l.id,'marketplace_code',m.code,'marketplace_name',m.name,
  'external_listing_id',l.external_listing_id,'canonical_url',l.canonical_url,
  'base_title',l.title,'title',coalesce(o.title,l.title),
  'base_listing_status',l.listing_status,'listing_status',coalesce(o.listing_status,l.listing_status),
  'base_observed_year',l.observed_year,'observed_year',coalesce(o.observed_year,l.observed_year),
  'image_url',coalesce(
    o.image_url,
    (
      select nullif(sr.normalized_payload->>'image_url','')
      from public.commerce_preview_source_rows sr
      where sr.matched_listing_id=l.id and sr.is_header=false
        and nullif(sr.normalized_payload->>'image_url','') is not null
      order by sr.imported_at desc nulls last,sr.id desc
      limit 1
    )
  ),
  'price',coalesce(o.price,nullif(l.raw_metadata->>'price',''),nullif(l.raw_metadata->>'sale_price','')),
  'category',coalesce(o.category,nullif(l.raw_metadata->>'marketplace_category',''),nullif(l.raw_metadata->>'category','')),
  'note',o.note,'sync_status',coalesce(o.sync_status,'NONE'),
  'updated_by',o.updated_by,'updated_at',o.updated_at,
  'platform_skus',coalesce((
    select jsonb_agg(distinct coalesce(nullif(lp.platform_sku,''),ps.sku)) filter (where coalesce(nullif(lp.platform_sku,''),ps.sku) is not null)
    from public.commerce_preview_listing_products lp
    left join public.commerce_preview_product_skus ps on ps.id=lp.product_sku_id
    where lp.listing_id=l.id
  ),'[]'::jsonb),
  'products',coalesce((
    select jsonb_agg(jsonb_build_object(
      'product_id',p.id,'name',p.name,'platform_sku',lp.platform_sku,'variation_name',lp.variation_name
    ) order by p.name,p.id)
    from public.commerce_preview_listing_products lp
    join public.commerce_preview_products p on p.id=lp.product_id
    where lp.listing_id=l.id
  ),'[]'::jsonb),
  'history',coalesce((
    select jsonb_agg(jsonb_build_object(
      'id',h.id,'batch_token',h.batch_token,'field_name',h.field_name,
      'old_value',h.old_value,'new_value',h.new_value,'operator_name',h.operator_name,'created_at',h.created_at
    ) order by h.created_at desc,h.id desc)
    from (
      select * from public.commerce_preview_listing_edit_history
      where listing_id=l.id order by created_at desc,id desc limit 20
    ) h
  ),'[]'::jsonb)
)
from public.commerce_preview_listings l
join public.commerce_marketplaces m on m.id=l.marketplace_id
left join public.commerce_preview_listing_overrides o on o.listing_id=l.id
where l.id=p_listing_id;
$$;

create or replace function public.commerce_preview_enrich_management_platforms_v1(p_platforms jsonb)
returns jsonb
language sql
stable
security invoker
set search_path = public
as $$
select coalesce(jsonb_agg(
  p.platform || jsonb_build_object('items',coalesce(e.items,'[]'::jsonb))
  order by p.ord
),'[]'::jsonb)
from jsonb_array_elements(coalesce(p_platforms,'[]'::jsonb)) with ordinality p(platform,ord)
left join lateral (
  select jsonb_agg(
    i.item || jsonb_build_object(
      'listing_id',l.id,
      'listing_title',coalesce(o.title,l.title,i.item->>'product_name'),
      'listing_status',coalesce(o.listing_status,i.item->>'listing_status'),
      'edition_year',coalesce(o.observed_year,case when (i.item->>'edition_year') ~ '^[0-9]+$' then (i.item->>'edition_year')::integer end),
      'image_url',coalesce(o.image_url,nullif(i.item->>'image_url','')),
      'price',o.price,'listing_category',o.category,'listing_note',o.note,
      'sync_status',coalesce(o.sync_status,'NONE')
    )
    order by i.iord
  ) as items
  from jsonb_array_elements(coalesce(p.platform->'items','[]'::jsonb)) with ordinality i(item,iord)
  left join public.commerce_preview_source_rows sr
    on sr.id=case when (i.item->>'source_row_id') ~ '^[0-9]+$' then (i.item->>'source_row_id')::bigint end
  left join public.commerce_preview_listings l on l.id=sr.matched_listing_id
  left join public.commerce_preview_listing_overrides o on o.listing_id=l.id
) e on true;
$$;

create or replace function public.commerce_preview_management_products_v3(
  p_search text default null,
  p_category text default null,
  p_year integer default null,
  p_presence text default 'LINKED',
  p_limit integer default 24,
  p_offset integer default 0
)
returns table(
  card_key text,product_id bigint,product_name text,master_sku text,category_name text,
  edition_year integer,image_url text,platform_count integer,presence_type text,platforms jsonb,
  link_review_status text,suggested_product_id bigint,candidate_count integer,total_count bigint
)
language sql
stable
security invoker
set search_path = public
as $$
select
  b.card_key,b.product_id,b.product_name,b.master_sku,b.category_name,b.edition_year,b.image_url,
  b.platform_count,b.presence_type,
  public.commerce_preview_enrich_management_platforms_v1(b.platforms) as platforms,
  b.link_review_status,b.suggested_product_id,b.candidate_count,b.total_count
from public.commerce_preview_management_products_v2(p_search,p_category,p_year,p_presence,p_limit,p_offset) b;
$$;

revoke execute on function public.commerce_edit_listing_v1(bigint,jsonb,text,uuid) from public, anon, authenticated;
revoke execute on function public.commerce_bulk_edit_listings_v1(bigint[],text,text,text) from public, anon, authenticated;
revoke execute on function public.commerce_queue_listing_sync_v1(bigint,text) from public, anon, authenticated;
revoke execute on function public.commerce_listing_editor_v1(bigint) from public, anon, authenticated;
revoke execute on function public.commerce_enrich_management_platforms_v1(jsonb) from public, anon, authenticated;
revoke execute on function public.commerce_management_products_v3(text,text,integer,text,integer,integer) from public, anon, authenticated;
grant execute on function public.commerce_edit_listing_v1(bigint,jsonb,text,uuid) to service_role;
grant execute on function public.commerce_bulk_edit_listings_v1(bigint[],text,text,text) to service_role;
grant execute on function public.commerce_queue_listing_sync_v1(bigint,text) to service_role;
grant execute on function public.commerce_listing_editor_v1(bigint) to service_role;
grant execute on function public.commerce_enrich_management_platforms_v1(jsonb) to service_role;
grant execute on function public.commerce_management_products_v3(text,text,integer,text,integer,integer) to service_role;

revoke execute on function public.commerce_preview_edit_listing_v1(bigint,jsonb,text,uuid) from public, anon, authenticated;
revoke execute on function public.commerce_preview_bulk_edit_listings_v1(bigint[],text,text,text) from public, anon, authenticated;
revoke execute on function public.commerce_preview_queue_listing_sync_v1(bigint,text) from public, anon, authenticated;
revoke execute on function public.commerce_preview_listing_editor_v1(bigint) from public, anon, authenticated;
revoke execute on function public.commerce_preview_enrich_management_platforms_v1(jsonb) from public, anon, authenticated;
revoke execute on function public.commerce_preview_management_products_v3(text,text,integer,text,integer,integer) from public, anon, authenticated;
grant execute on function public.commerce_preview_edit_listing_v1(bigint,jsonb,text,uuid) to service_role;
grant execute on function public.commerce_preview_bulk_edit_listings_v1(bigint[],text,text,text) to service_role;
grant execute on function public.commerce_preview_queue_listing_sync_v1(bigint,text) to service_role;
grant execute on function public.commerce_preview_listing_editor_v1(bigint) to service_role;
grant execute on function public.commerce_preview_enrich_management_platforms_v1(jsonb) to service_role;
grant execute on function public.commerce_preview_management_products_v3(text,text,integer,text,integer,integer) to service_role;
