-- NISTI ID — Supabase PostgreSQL target schema
-- Source compatibility baseline: D1 migrations 0001..0013 on main/v8.24.4.
-- Images stay in R2. Visual retrieval stays in Cloudflare Vectorize.
-- Browser clients must not access these tables directly; RLS is enabled and
-- the Cloudflare Worker will use a server-side Supabase credential.

CREATE TABLE public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku TEXT NOT NULL UNIQUE,
  miolo_code TEXT NOT NULL,
  capa_code TEXT NOT NULL,
  acabamento_code TEXT NOT NULL,
  wireo_code TEXT NOT NULL,
  tassel_code TEXT NOT NULL,
  elastico_code TEXT NOT NULL,
  nome TEXT,
  variacao TEXT,
  image_key TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.product_platforms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  platform TEXT NOT NULL,
  link TEXT,
  CONSTRAINT product_platform_unique UNIQUE (product_id, platform)
);

CREATE TABLE public.cover_embeddings (
  capa_code TEXT PRIMARY KEY,
  image_key TEXT NOT NULL,
  embedding_model TEXT NOT NULL,
  dimensions INTEGER NOT NULL,
  embedding_json TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.recognition_daily (
  day TEXT PRIMARY KEY,
  attempts INTEGER NOT NULL DEFAULT 0,
  successes INTEGER NOT NULL DEFAULT 0,
  unmatched INTEGER NOT NULL DEFAULT 0,
  system_errors INTEGER NOT NULL DEFAULT 0,
  embedding_requests INTEGER NOT NULL DEFAULT 0,
  generation_requests INTEGER NOT NULL DEFAULT 0,
  total_ms BIGINT NOT NULL DEFAULT 0,
  last_success_at TIMESTAMPTZ,
  last_unmatched_at TIMESTAMPTZ,
  last_error_at TIMESTAMPTZ,
  last_error_message TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.recognition_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  day TEXT NOT NULL,
  kind TEXT NOT NULL,
  http_status INTEGER NOT NULL,
  product_id BIGINT,
  capa_code TEXT,
  sku TEXT,
  confidence DOUBLE PRECISION,
  retrieval_score DOUBLE PRECISION,
  identified_by TEXT,
  error_message TEXT,
  total_ms BIGINT NOT NULL DEFAULT 0,
  embedding_ms BIGINT,
  gemini_ms BIGINT,
  retrieval_top1 DOUBLE PRECISION,
  retrieval_top1_code TEXT,
  retrieval_top2 DOUBLE PRECISION,
  retrieval_top2_code TEXT,
  retrieval_margin DOUBLE PRECISION,
  candidate_count INTEGER,
  verification_mode TEXT,
  accepted_by TEXT,
  model TEXT,
  verifier_reason_code TEXT,
  verifier_evidence TEXT,
  vectorize_ms BIGINT,
  local_cv_ms BIGINT,
  reference_load_ms BIGINT,
  retrieval_source TEXT,
  reused_candidates INTEGER,
  pipeline_version TEXT,
  reference_candidate_count INTEGER,
  vector_top_k INTEGER,
  operator_name TEXT,
  operator_id TEXT
);

CREATE TABLE public.cover_visual_references (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  capa_code TEXT NOT NULL,
  image_key TEXT NOT NULL,
  source_product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
  reference_kind TEXT NOT NULL DEFAULT 'product',
  active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0,1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT cover_visual_references_capa_image_unique UNIQUE (capa_code, image_key)
);

CREATE TABLE public.cover_reference_embeddings (
  reference_id BIGINT PRIMARY KEY REFERENCES public.cover_visual_references(id) ON DELETE CASCADE,
  embedding_model TEXT NOT NULL,
  dimensions INTEGER NOT NULL,
  embedding_json TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.cover_visual_signatures (
  capa_code TEXT PRIMARY KEY,
  reference_id BIGINT REFERENCES public.cover_visual_references(id) ON DELETE SET NULL,
  signature_model TEXT NOT NULL,
  signature_json TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL DEFAULT 'new_cover',
  capa_code TEXT NOT NULL UNIQUE,
  product_id BIGINT,
  sku TEXT,
  product_name TEXT,
  variacao TEXT,
  platform TEXT,
  image_key TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.notification_reads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notification_id BIGINT NOT NULL REFERENCES public.notifications(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL,
  read_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT notification_reads_notification_user_unique UNIQUE (notification_id, user_id)
);

CREATE TABLE public.push_subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  endpoint TEXT NOT NULL UNIQUE,
  p256dh TEXT NOT NULL,
  auth TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.scan_occurrences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_key TEXT NOT NULL,
  platform TEXT,
  suggested_capa_code TEXT,
  confidence DOUBLE PRECISION,
  error_reason TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','trained','dismissed')),
  trained_capa_code TEXT,
  trained_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.geometric_shadow_evidence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evidence_token TEXT NOT NULL UNIQUE,
  photo_sha256 TEXT NOT NULL,
  platform TEXT NOT NULL,
  operator_id TEXT,
  operator_name TEXT,
  occurrence_id BIGINT,
  shadow_version TEXT NOT NULL DEFAULT 'v8.18',
  gate_version TEXT NOT NULL DEFAULT 'strict_core_v816',
  retrieval_fastpath_eligible INTEGER NOT NULL DEFAULT 0,
  retrieval_capa_code TEXT,
  geometric_evaluated INTEGER NOT NULL DEFAULT 0,
  geometric_eligible INTEGER NOT NULL DEFAULT 0,
  geometric_capa_code TEXT,
  content_independent INTEGER NOT NULL DEFAULT 1,
  same_content_reference_count INTEGER NOT NULL DEFAULT 0,
  evidence_json TEXT NOT NULL,
  confirmed_capa_code TEXT,
  confirmation_source TEXT,
  confirmed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_products_capa ON public.products(capa_code);
CREATE INDEX idx_products_finish ON public.products(wireo_code, tassel_code, elastico_code);
CREATE INDEX idx_products_capa_normalized_id ON public.products((upper(btrim(capa_code))), id);
CREATE INDEX idx_platform_product ON public.product_platforms(product_id);
CREATE INDEX idx_product_platforms_platform_normalized_product ON public.product_platforms((upper(btrim(platform))), product_id, id);
CREATE INDEX idx_cover_embeddings_updated_at ON public.cover_embeddings(updated_at);
CREATE INDEX idx_recognition_events_created_at ON public.recognition_events(created_at DESC);
CREATE INDEX idx_recognition_events_kind_created_at ON public.recognition_events(kind, created_at DESC);
CREATE INDEX idx_recognition_events_kind_id ON public.recognition_events(kind, id DESC);
CREATE INDEX idx_recognition_events_operator_name_created_at ON public.recognition_events(operator_name, created_at DESC);
CREATE INDEX idx_recognition_events_operator_name_id ON public.recognition_events(operator_name, id DESC);
CREATE INDEX idx_recognition_events_operator_kind_id ON public.recognition_events(operator_name, kind, id DESC);
CREATE INDEX idx_recognition_events_operator_id ON public.recognition_events(operator_id);
CREATE INDEX idx_cover_visual_references_cover_active ON public.cover_visual_references(capa_code, active);
CREATE INDEX idx_cover_visual_references_product ON public.cover_visual_references(source_product_id);
CREATE INDEX idx_cover_visual_references_capa_normalized_active_id ON public.cover_visual_references((upper(btrim(capa_code))), active, id);
CREATE INDEX idx_cover_reference_embeddings_updated_at ON public.cover_reference_embeddings(updated_at);
CREATE INDEX idx_cover_visual_signatures_reference ON public.cover_visual_signatures(reference_id);
CREATE INDEX idx_notifications_created ON public.notifications(created_at DESC);
CREATE INDEX idx_notifications_capa_normalized ON public.notifications((upper(btrim(capa_code))));
CREATE INDEX idx_notification_reads_user ON public.notification_reads(user_id, notification_id);
CREATE INDEX idx_scan_occurrences_status_created_at ON public.scan_occurrences(status, created_at DESC);
CREATE INDEX idx_geometric_shadow_evidence_photo ON public.geometric_shadow_evidence(platform, photo_sha256);
CREATE INDEX idx_geometric_shadow_evidence_occurrence ON public.geometric_shadow_evidence(occurrence_id);
CREATE INDEX idx_geometric_shadow_evidence_confirmed ON public.geometric_shadow_evidence(confirmed_capa_code, confirmed_at);
CREATE INDEX idx_geometric_shadow_evidence_independent ON public.geometric_shadow_evidence(content_independent, confirmed_at);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_platforms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cover_embeddings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recognition_daily ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recognition_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cover_visual_references ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cover_reference_embeddings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cover_visual_signatures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_reads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scan_occurrences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.geometric_shadow_evidence ENABLE ROW LEVEL SECURITY;
