begin;

create table if not exists public.commerce_marketplace_snapshots (
  id bigint generated by default as identity primary key,
  marketplace_id bigint not null references public.commerce_marketplaces(id) on delete restrict,
  external_listing_id text not null,
  snapshot_key text not null,
  source_account_id text,
  source_basic_filename text,
  source_media_filename text,
  source_basic_sha256 text,
  source_media_sha256 text,
  parent_sku text,
  title text,
  description text,
  marketplace_category text,
  cover_image_url text,
  product_image_urls jsonb not null default '[]'::jsonb,
  variation_name text,
  variation_options jsonb not null default '[]'::jsonb,
  failure_reason text,
  listing_id bigint references public.commerce_listings(id) on delete set null,
  match_status text not null default 'NEW_PENDING',
  ingested_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint commerce_marketplace_snapshots_match_status_ck
    check (match_status in ('MATCHED','NEW_PENDING','CONFLICT')),
  constraint commerce_marketplace_snapshots_unique
    unique (marketplace_id, external_listing_id, snapshot_key)
);

create index if not exists commerce_marketplace_snapshots_listing_idx
  on public.commerce_marketplace_snapshots(listing_id, ingested_at desc);
create index if not exists commerce_marketplace_snapshots_status_idx
  on public.commerce_marketplace_snapshots(marketplace_id, match_status, ingested_at desc);

create table if not exists public.commerce_preview_marketplace_snapshots (
  id bigint generated by default as identity primary key,
  marketplace_id bigint not null references public.commerce_preview_marketplaces(id) on delete restrict,
  external_listing_id text not null,
  snapshot_key text not null,
  source_account_id text,
  source_basic_filename text,
  source_media_filename text,
  source_basic_sha256 text,
  source_media_sha256 text,
  parent_sku text,
  title text,
  description text,
  marketplace_category text,
  cover_image_url text,
  product_image_urls jsonb not null default '[]'::jsonb,
  variation_name text,
  variation_options jsonb not null default '[]'::jsonb,
  failure_reason text,
  listing_id bigint references public.commerce_preview_listings(id) on delete set null,
  match_status text not null default 'NEW_PENDING',
  ingested_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint commerce_preview_marketplace_snapshots_match_status_ck
    check (match_status in ('MATCHED','NEW_PENDING','CONFLICT')),
  constraint commerce_preview_marketplace_snapshots_unique
    unique (marketplace_id, external_listing_id, snapshot_key)
);

create index if not exists commerce_preview_marketplace_snapshots_listing_idx
  on public.commerce_preview_marketplace_snapshots(listing_id, ingested_at desc);
create index if not exists commerce_preview_marketplace_snapshots_status_idx
  on public.commerce_preview_marketplace_snapshots(marketplace_id, match_status, ingested_at desc);

create or replace function public.commerce_ingest_shopee_snapshot_v1(
  p_items jsonb,
  p_snapshot_key text,
  p_source_account_id text,
  p_source_basic_filename text,
  p_source_media_filename text,
  p_source_basic_sha256 text,
  p_source_media_sha256 text
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_marketplace_id bigint;
  v_item jsonb;
  v_external_id text;
  v_listing_id bigint;
  v_listing_count integer;
  v_existing_external text;
  v_match_status text;
  v_matched integer := 0;
  v_pending integer := 0;
  v_conflicts integer := 0;
  v_title_updates integer := 0;
  v_external_id_fills integer := 0;
  v_old_title text;
  v_title text;
begin
  if jsonb_typeof(p_items) <> 'array' then
    raise exception 'items_must_be_array' using errcode = '22023';
  end if;
  if nullif(btrim(coalesce(p_snapshot_key,'')),'') is null then
    raise exception 'snapshot_key_required' using errcode = '22023';
  end if;

  select id into v_marketplace_id
  from public.commerce_marketplaces
  where upper(code) = 'SHOPEE'
  limit 1;

  if v_marketplace_id is null then
    raise exception 'shopee_marketplace_missing' using errcode = 'P0001';
  end if;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_external_id := nullif(btrim(coalesce(v_item->>'external_listing_id','')),'');
    if v_external_id is null or v_external_id !~ '^[0-9]+$' then
      raise exception 'external_listing_id_invalid' using errcode = '22023';
    end if;

    select count(*), min(l.id)
      into v_listing_count, v_listing_id
    from public.commerce_listings l
    where l.marketplace_id = v_marketplace_id
      and (
        l.external_listing_id = v_external_id
        or l.canonical_url ~ ('/(product/[0-9]+/|portal/product/)' || v_external_id || '([/?#]|$)')
      );

    v_match_status := case
      when v_listing_count = 0 then 'NEW_PENDING'
      when v_listing_count = 1 then 'MATCHED'
      else 'CONFLICT'
    end;

    if v_match_status = 'MATCHED' then
      select l.external_listing_id,l.title
        into v_existing_external,v_old_title
      from public.commerce_listings l
      where l.id = v_listing_id;

      if nullif(btrim(coalesce(v_existing_external,'')),'') is not null
         and v_existing_external <> v_external_id then
        v_match_status := 'CONFLICT';
      end if;
    end if;

    insert into public.commerce_marketplace_snapshots(
      marketplace_id,external_listing_id,snapshot_key,source_account_id,
      source_basic_filename,source_media_filename,source_basic_sha256,source_media_sha256,
      parent_sku,title,description,marketplace_category,cover_image_url,
      product_image_urls,variation_name,variation_options,failure_reason,
      listing_id,match_status,updated_at
    )
    values(
      v_marketplace_id,
      v_external_id,
      btrim(p_snapshot_key),
      nullif(btrim(coalesce(p_source_account_id,'')),''),
      nullif(btrim(coalesce(p_source_basic_filename,'')),''),
      nullif(btrim(coalesce(p_source_media_filename,'')),''),
      nullif(btrim(coalesce(p_source_basic_sha256,'')),''),
      nullif(btrim(coalesce(p_source_media_sha256,'')),''),
      nullif(btrim(coalesce(v_item->>'parent_sku','')),''),
      nullif(btrim(coalesce(v_item->>'title','')),''),
      v_item->>'description',
      nullif(btrim(coalesce(v_item->>'marketplace_category','')),''),
      nullif(btrim(coalesce(v_item->>'cover_image_url','')),''),
      case when jsonb_typeof(v_item->'product_image_urls')='array'
        then v_item->'product_image_urls' else '[]'::jsonb end,
      nullif(btrim(coalesce(v_item->>'variation_name','')),''),
      case when jsonb_typeof(v_item->'variation_options')='array'
        then v_item->'variation_options' else '[]'::jsonb end,
      nullif(btrim(coalesce(v_item->>'failure_reason','')),''),
      case when v_match_status='MATCHED' then v_listing_id else null end,
      v_match_status,
      now()
    )
    on conflict (marketplace_id,external_listing_id,snapshot_key)
    do update set
      source_account_id=excluded.source_account_id,
      source_basic_filename=excluded.source_basic_filename,
      source_media_filename=excluded.source_media_filename,
      source_basic_sha256=excluded.source_basic_sha256,
      source_media_sha256=excluded.source_media_sha256,
      parent_sku=excluded.parent_sku,
      title=excluded.title,
      description=excluded.description,
      marketplace_category=excluded.marketplace_category,
      cover_image_url=excluded.cover_image_url,
      product_image_urls=excluded.product_image_urls,
      variation_name=excluded.variation_name,
      variation_options=excluded.variation_options,
      failure_reason=excluded.failure_reason,
      listing_id=excluded.listing_id,
      match_status=excluded.match_status,
      updated_at=now();

    if v_match_status = 'MATCHED' then
      v_title := nullif(btrim(coalesce(v_item->>'title','')),'');
      if v_title is not null and v_old_title is distinct from v_title then
        v_title_updates := v_title_updates + 1;
      end if;
      if nullif(btrim(coalesce(v_existing_external,'')),'') is null then
        v_external_id_fills := v_external_id_fills + 1;
      end if;

      update public.commerce_listings
      set
        external_listing_id = coalesce(nullif(btrim(external_listing_id),''), v_external_id),
        title = coalesce(v_title,title),
        raw_metadata = coalesce(raw_metadata,'{}'::jsonb) || jsonb_build_object(
          'shopee_snapshot',
          jsonb_build_object(
            'snapshot_key',btrim(p_snapshot_key),
            'external_listing_id',v_external_id,
            'parent_sku',nullif(btrim(coalesce(v_item->>'parent_sku','')),''),
            'marketplace_category',nullif(btrim(coalesce(v_item->>'marketplace_category','')),''),
            'cover_image_url',nullif(btrim(coalesce(v_item->>'cover_image_url','')),''),
            'product_image_urls',case when jsonb_typeof(v_item->'product_image_urls')='array' then v_item->'product_image_urls' else '[]'::jsonb end,
            'variation_name',nullif(btrim(coalesce(v_item->>'variation_name','')),''),
            'variation_options',case when jsonb_typeof(v_item->'variation_options')='array' then v_item->'variation_options' else '[]'::jsonb end,
            'source_basic_filename',nullif(btrim(coalesce(p_source_basic_filename,'')),''),
            'source_media_filename',nullif(btrim(coalesce(p_source_media_filename,'')),''),
            'ingested_at',now()
          )
        ),
        updated_at=now()
      where id=v_listing_id;

      v_matched := v_matched + 1;
    elsif v_match_status='NEW_PENDING' then
      v_pending := v_pending + 1;
    else
      v_conflicts := v_conflicts + 1;
    end if;
  end loop;

  return jsonb_build_object(
    'snapshot_key',btrim(p_snapshot_key),
    'processed',jsonb_array_length(p_items),
    'matched',v_matched,
    'new_pending',v_pending,
    'conflicts',v_conflicts,
    'title_updates',v_title_updates,
    'external_id_fills',v_external_id_fills
  );
end;
$$;

create or replace function public.commerce_preview_ingest_shopee_snapshot_v1(
  p_items jsonb,
  p_snapshot_key text,
  p_source_account_id text,
  p_source_basic_filename text,
  p_source_media_filename text,
  p_source_basic_sha256 text,
  p_source_media_sha256 text
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_marketplace_id bigint;
  v_item jsonb;
  v_external_id text;
  v_listing_id bigint;
  v_listing_count integer;
  v_existing_external text;
  v_match_status text;
  v_matched integer := 0;
  v_pending integer := 0;
  v_conflicts integer := 0;
  v_title_updates integer := 0;
  v_external_id_fills integer := 0;
  v_old_title text;
  v_title text;
begin
  if jsonb_typeof(p_items) <> 'array' then
    raise exception 'items_must_be_array' using errcode = '22023';
  end if;
  if nullif(btrim(coalesce(p_snapshot_key,'')),'') is null then
    raise exception 'snapshot_key_required' using errcode = '22023';
  end if;

  select id into v_marketplace_id
  from public.commerce_preview_marketplaces
  where upper(code) = 'SHOPEE'
  limit 1;

  if v_marketplace_id is null then
    raise exception 'shopee_marketplace_missing' using errcode = 'P0001';
  end if;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_external_id := nullif(btrim(coalesce(v_item->>'external_listing_id','')),'');
    if v_external_id is null or v_external_id !~ '^[0-9]+$' then
      raise exception 'external_listing_id_invalid' using errcode = '22023';
    end if;

    select count(*), min(l.id)
      into v_listing_count, v_listing_id
    from public.commerce_preview_listings l
    where l.marketplace_id = v_marketplace_id
      and (
        l.external_listing_id = v_external_id
        or l.canonical_url ~ ('/(product/[0-9]+/|portal/product/)' || v_external_id || '([/?#]|$)')
      );

    v_match_status := case
      when v_listing_count = 0 then 'NEW_PENDING'
      when v_listing_count = 1 then 'MATCHED'
      else 'CONFLICT'
    end;

    if v_match_status = 'MATCHED' then
      select l.external_listing_id,l.title
        into v_existing_external,v_old_title
      from public.commerce_preview_listings l
      where l.id = v_listing_id;

      if nullif(btrim(coalesce(v_existing_external,'')),'') is not null
         and v_existing_external <> v_external_id then
        v_match_status := 'CONFLICT';
      end if;
    end if;

    insert into public.commerce_preview_marketplace_snapshots(
      marketplace_id,external_listing_id,snapshot_key,source_account_id,
      source_basic_filename,source_media_filename,source_basic_sha256,source_media_sha256,
      parent_sku,title,description,marketplace_category,cover_image_url,
      product_image_urls,variation_name,variation_options,failure_reason,
      listing_id,match_status,updated_at
    )
    values(
      v_marketplace_id,
      v_external_id,
      btrim(p_snapshot_key),
      nullif(btrim(coalesce(p_source_account_id,'')),''),
      nullif(btrim(coalesce(p_source_basic_filename,'')),''),
      nullif(btrim(coalesce(p_source_media_filename,'')),''),
      nullif(btrim(coalesce(p_source_basic_sha256,'')),''),
      nullif(btrim(coalesce(p_source_media_sha256,'')),''),
      nullif(btrim(coalesce(v_item->>'parent_sku','')),''),
      nullif(btrim(coalesce(v_item->>'title','')),''),
      v_item->>'description',
      nullif(btrim(coalesce(v_item->>'marketplace_category','')),''),
      nullif(btrim(coalesce(v_item->>'cover_image_url','')),''),
      case when jsonb_typeof(v_item->'product_image_urls')='array'
        then v_item->'product_image_urls' else '[]'::jsonb end,
      nullif(btrim(coalesce(v_item->>'variation_name','')),''),
      case when jsonb_typeof(v_item->'variation_options')='array'
        then v_item->'variation_options' else '[]'::jsonb end,
      nullif(btrim(coalesce(v_item->>'failure_reason','')),''),
      case when v_match_status='MATCHED' then v_listing_id else null end,
      v_match_status,
      now()
    )
    on conflict (marketplace_id,external_listing_id,snapshot_key)
    do update set
      source_account_id=excluded.source_account_id,
      source_basic_filename=excluded.source_basic_filename,
      source_media_filename=excluded.source_media_filename,
      source_basic_sha256=excluded.source_basic_sha256,
      source_media_sha256=excluded.source_media_sha256,
      parent_sku=excluded.parent_sku,
      title=excluded.title,
      description=excluded.description,
      marketplace_category=excluded.marketplace_category,
      cover_image_url=excluded.cover_image_url,
      product_image_urls=excluded.product_image_urls,
      variation_name=excluded.variation_name,
      variation_options=excluded.variation_options,
      failure_reason=excluded.failure_reason,
      listing_id=excluded.listing_id,
      match_status=excluded.match_status,
      updated_at=now();

    if v_match_status = 'MATCHED' then
      v_title := nullif(btrim(coalesce(v_item->>'title','')),'');
      if v_title is not null and v_old_title is distinct from v_title then
        v_title_updates := v_title_updates + 1;
      end if;
      if nullif(btrim(coalesce(v_existing_external,'')),'') is null then
        v_external_id_fills := v_external_id_fills + 1;
      end if;

      update public.commerce_preview_listings
      set
        external_listing_id = coalesce(nullif(btrim(external_listing_id),''), v_external_id),
        title = coalesce(v_title,title),
        raw_metadata = coalesce(raw_metadata,'{}'::jsonb) || jsonb_build_object(
          'shopee_snapshot',
          jsonb_build_object(
            'snapshot_key',btrim(p_snapshot_key),
            'external_listing_id',v_external_id,
            'parent_sku',nullif(btrim(coalesce(v_item->>'parent_sku','')),''),
            'marketplace_category',nullif(btrim(coalesce(v_item->>'marketplace_category','')),''),
            'cover_image_url',nullif(btrim(coalesce(v_item->>'cover_image_url','')),''),
            'product_image_urls',case when jsonb_typeof(v_item->'product_image_urls')='array' then v_item->'product_image_urls' else '[]'::jsonb end,
            'variation_name',nullif(btrim(coalesce(v_item->>'variation_name','')),''),
            'variation_options',case when jsonb_typeof(v_item->'variation_options')='array' then v_item->'variation_options' else '[]'::jsonb end,
            'source_basic_filename',nullif(btrim(coalesce(p_source_basic_filename,'')),''),
            'source_media_filename',nullif(btrim(coalesce(p_source_media_filename,'')),''),
            'ingested_at',now()
          )
        ),
        updated_at=now()
      where id=v_listing_id;

      v_matched := v_matched + 1;
    elsif v_match_status='NEW_PENDING' then
      v_pending := v_pending + 1;
    else
      v_conflicts := v_conflicts + 1;
    end if;
  end loop;

  return jsonb_build_object(
    'snapshot_key',btrim(p_snapshot_key),
    'processed',jsonb_array_length(p_items),
    'matched',v_matched,
    'new_pending',v_pending,
    'conflicts',v_conflicts,
    'title_updates',v_title_updates,
    'external_id_fills',v_external_id_fills
  );
end;
$$;

create or replace function public.commerce_list_shopee_snapshot_v1(
  p_search text default null,
  p_match_status text default null,
  p_limit integer default 50,
  p_offset integer default 0
)
returns table(
  snapshot_id bigint,
  external_listing_id text,
  parent_sku text,
  title text,
  marketplace_category text,
  cover_image_url text,
  product_image_urls jsonb,
  variation_name text,
  variation_options jsonb,
  listing_id bigint,
  match_status text,
  canonical_url text,
  listing_status text,
  product_count bigint,
  snapshot_key text,
  ingested_at timestamptz,
  total_count bigint
)
language sql
stable
security invoker
set search_path=public
as $$
  with latest as (
    select distinct on (s.external_listing_id)
      s.*
    from public.commerce_marketplace_snapshots s
    join public.commerce_marketplaces m on m.id=s.marketplace_id
    where upper(m.code)='SHOPEE'
    order by s.external_listing_id,s.ingested_at desc,s.id desc
  ), filtered as (
    select
      s.id snapshot_id,s.external_listing_id,s.parent_sku,s.title,s.marketplace_category,
      s.cover_image_url,s.product_image_urls,s.variation_name,s.variation_options,
      s.listing_id,s.match_status,l.canonical_url,l.listing_status,
      count(distinct lp.product_id) filter (where lp.relation_status<>'REMOVED') as product_count,
      s.snapshot_key,s.ingested_at
    from latest s
    left join public.commerce_listings l on l.id=s.listing_id
    left join public.commerce_listing_products lp on lp.listing_id=l.id
    where (nullif(btrim(coalesce(p_match_status,'')),'') is null or s.match_status=upper(btrim(p_match_status)))
      and (
        nullif(btrim(coalesce(p_search,'')),'') is null
        or s.external_listing_id ilike '%'||btrim(p_search)||'%'
        or s.parent_sku ilike '%'||btrim(p_search)||'%'
        or s.title ilike '%'||btrim(p_search)||'%'
      )
    group by s.id,s.external_listing_id,s.parent_sku,s.title,s.marketplace_category,
      s.cover_image_url,s.product_image_urls,s.variation_name,s.variation_options,
      s.listing_id,s.match_status,l.canonical_url,l.listing_status,s.snapshot_key,s.ingested_at
  ), counted as (
    select f.*,count(*) over() total_count
    from filtered f
  )
  select *
  from counted
  order by case match_status when 'NEW_PENDING' then 0 when 'CONFLICT' then 1 else 2 end,
           lower(coalesce(title,'')),external_listing_id
  limit greatest(1,least(coalesce(p_limit,50),100))
  offset greatest(coalesce(p_offset,0),0);
$$;

create or replace function public.commerce_preview_list_shopee_snapshot_v1(
  p_search text default null,
  p_match_status text default null,
  p_limit integer default 50,
  p_offset integer default 0
)
returns table(
  snapshot_id bigint,
  external_listing_id text,
  parent_sku text,
  title text,
  marketplace_category text,
  cover_image_url text,
  product_image_urls jsonb,
  variation_name text,
  variation_options jsonb,
  listing_id bigint,
  match_status text,
  canonical_url text,
  listing_status text,
  product_count bigint,
  snapshot_key text,
  ingested_at timestamptz,
  total_count bigint
)
language sql
stable
security invoker
set search_path=public
as $$
  with latest as (
    select distinct on (s.external_listing_id)
      s.*
    from public.commerce_preview_marketplace_snapshots s
    join public.commerce_preview_marketplaces m on m.id=s.marketplace_id
    where upper(m.code)='SHOPEE'
    order by s.external_listing_id,s.ingested_at desc,s.id desc
  ), filtered as (
    select
      s.id snapshot_id,s.external_listing_id,s.parent_sku,s.title,s.marketplace_category,
      s.cover_image_url,s.product_image_urls,s.variation_name,s.variation_options,
      s.listing_id,s.match_status,l.canonical_url,l.listing_status,
      count(distinct lp.product_id) filter (where lp.relation_status<>'REMOVED') as product_count,
      s.snapshot_key,s.ingested_at
    from latest s
    left join public.commerce_preview_listings l on l.id=s.listing_id
    left join public.commerce_preview_listing_products lp on lp.listing_id=l.id
    where (nullif(btrim(coalesce(p_match_status,'')),'') is null or s.match_status=upper(btrim(p_match_status)))
      and (
        nullif(btrim(coalesce(p_search,'')),'') is null
        or s.external_listing_id ilike '%'||btrim(p_search)||'%'
        or s.parent_sku ilike '%'||btrim(p_search)||'%'
        or s.title ilike '%'||btrim(p_search)||'%'
      )
    group by s.id,s.external_listing_id,s.parent_sku,s.title,s.marketplace_category,
      s.cover_image_url,s.product_image_urls,s.variation_name,s.variation_options,
      s.listing_id,s.match_status,l.canonical_url,l.listing_status,s.snapshot_key,s.ingested_at
  ), counted as (
    select f.*,count(*) over() total_count
    from filtered f
  )
  select *
  from counted
  order by case match_status when 'NEW_PENDING' then 0 when 'CONFLICT' then 1 else 2 end,
           lower(coalesce(title,'')),external_listing_id
  limit greatest(1,least(coalesce(p_limit,50),100))
  offset greatest(coalesce(p_offset,0),0);
$$;

create or replace function public.commerce_list_products_v2(
  p_search text default null,
  p_marketplace_code text default null,
  p_category_id bigint default null,
  p_internal_status text default null,
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  product_id bigint,
  name text,
  current_sku text,
  category_id bigint,
  category_name text,
  subcategory_id bigint,
  subcategory_name text,
  temporal_type text,
  edition_year integer,
  internal_status text,
  marketplace_count bigint,
  listing_count bigint,
  marketplace_codes text[],
  total_count bigint,
  thumbnail_url text,
  thumbnail_listing_id bigint
)
language sql
stable
security invoker
set search_path=public
as $$
  select
    p.product_id,p.name,p.current_sku,p.category_id,p.category_name,
    p.subcategory_id,p.subcategory_name,p.temporal_type,p.edition_year,
    p.internal_status,p.marketplace_count,p.listing_count,p.marketplace_codes,p.total_count,
    thumb.cover_image_url,thumb.listing_id
  from public.commerce_list_products_v1(
    p_search,p_marketplace_code,p_category_id,p_internal_status,p_limit,p_offset
  ) p
  left join lateral (
    select s.cover_image_url,s.listing_id
    from public.commerce_marketplace_snapshots s
    join public.commerce_listing_products lp
      on lp.listing_id=s.listing_id
     and lp.product_id=p.product_id
     and lp.relation_status<>'REMOVED'
    where s.match_status='MATCHED'
      and nullif(btrim(coalesce(s.cover_image_url,'')),'') is not null
    order by s.ingested_at desc,s.id desc
    limit 1
  ) thumb on true;
$$;

create or replace function public.commerce_preview_list_products_v2(
  p_search text default null,
  p_marketplace_code text default null,
  p_category_id bigint default null,
  p_internal_status text default null,
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  product_id bigint,
  name text,
  current_sku text,
  category_id bigint,
  category_name text,
  subcategory_id bigint,
  subcategory_name text,
  temporal_type text,
  edition_year integer,
  internal_status text,
  marketplace_count bigint,
  listing_count bigint,
  marketplace_codes text[],
  total_count bigint,
  thumbnail_url text,
  thumbnail_listing_id bigint
)
language sql
stable
security invoker
set search_path=public
as $$
  select
    p.product_id,p.name,p.current_sku,p.category_id,p.category_name,
    p.subcategory_id,p.subcategory_name,p.temporal_type,p.edition_year,
    p.internal_status,p.marketplace_count,p.listing_count,p.marketplace_codes,p.total_count,
    thumb.cover_image_url,thumb.listing_id
  from public.commerce_preview_list_products_v1(
    p_search,p_marketplace_code,p_category_id,p_internal_status,p_limit,p_offset
  ) p
  left join lateral (
    select s.cover_image_url,s.listing_id
    from public.commerce_preview_marketplace_snapshots s
    join public.commerce_preview_listing_products lp
      on lp.listing_id=s.listing_id
     and lp.product_id=p.product_id
     and lp.relation_status<>'REMOVED'
    where s.match_status='MATCHED'
      and nullif(btrim(coalesce(s.cover_image_url,'')),'') is not null
    order by s.ingested_at desc,s.id desc
    limit 1
  ) thumb on true;
$$;

create or replace function public.commerce_list_listings_v2(
  p_search text default null,
  p_marketplace_code text default null,
  p_listing_status text default null,
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  listing_id bigint,
  marketplace_code text,
  marketplace_name text,
  external_listing_id text,
  canonical_url text,
  title text,
  listing_status text,
  sales_status text,
  video_status text,
  observed_year integer,
  product_count bigint,
  platform_skus text[],
  last_checked_at timestamptz,
  total_count bigint,
  cover_image_url text,
  product_image_urls jsonb,
  variation_name text,
  variation_options jsonb,
  marketplace_category text,
  snapshot_key text
)
language sql
stable
security invoker
set search_path=public
as $$
  select
    l.listing_id,l.marketplace_code,l.marketplace_name,l.external_listing_id,l.canonical_url,l.title,
    l.listing_status,l.sales_status,l.video_status,l.observed_year,l.product_count,l.platform_skus,
    l.last_checked_at,l.total_count,
    s.cover_image_url,s.product_image_urls,s.variation_name,s.variation_options,
    s.marketplace_category,s.snapshot_key
  from public.commerce_list_listings_v1(
    p_search,p_marketplace_code,p_listing_status,p_limit,p_offset
  ) l
  left join lateral (
    select ms.cover_image_url,ms.product_image_urls,ms.variation_name,ms.variation_options,
           ms.marketplace_category,ms.snapshot_key
    from public.commerce_marketplace_snapshots ms
    where ms.listing_id=l.listing_id
      and ms.match_status='MATCHED'
    order by ms.ingested_at desc,ms.id desc
    limit 1
  ) s on true;
$$;

create or replace function public.commerce_preview_list_listings_v2(
  p_search text default null,
  p_marketplace_code text default null,
  p_listing_status text default null,
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  listing_id bigint,
  marketplace_code text,
  marketplace_name text,
  external_listing_id text,
  canonical_url text,
  title text,
  listing_status text,
  sales_status text,
  video_status text,
  observed_year integer,
  product_count bigint,
  platform_skus text[],
  last_checked_at timestamptz,
  total_count bigint,
  cover_image_url text,
  product_image_urls jsonb,
  variation_name text,
  variation_options jsonb,
  marketplace_category text,
  snapshot_key text
)
language sql
stable
security invoker
set search_path=public
as $$
  select
    l.listing_id,l.marketplace_code,l.marketplace_name,l.external_listing_id,l.canonical_url,l.title,
    l.listing_status,l.sales_status,l.video_status,l.observed_year,l.product_count,l.platform_skus,
    l.last_checked_at,l.total_count,
    s.cover_image_url,s.product_image_urls,s.variation_name,s.variation_options,
    s.marketplace_category,s.snapshot_key
  from public.commerce_preview_list_listings_v1(
    p_search,p_marketplace_code,p_listing_status,p_limit,p_offset
  ) l
  left join lateral (
    select ms.cover_image_url,ms.product_image_urls,ms.variation_name,ms.variation_options,
           ms.marketplace_category,ms.snapshot_key
    from public.commerce_preview_marketplace_snapshots ms
    where ms.listing_id=l.listing_id
      and ms.match_status='MATCHED'
    order by ms.ingested_at desc,ms.id desc
    limit 1
  ) s on true;
$$;

revoke all on table public.commerce_marketplace_snapshots from public,anon,authenticated;
revoke all on table public.commerce_preview_marketplace_snapshots from public,anon,authenticated;
grant select,insert,update on table public.commerce_marketplace_snapshots to service_role;
grant select,insert,update on table public.commerce_preview_marketplace_snapshots to service_role;
grant usage,select on sequence public.commerce_marketplace_snapshots_id_seq to service_role;
grant usage,select on sequence public.commerce_preview_marketplace_snapshots_id_seq to service_role;

revoke all on function public.commerce_ingest_shopee_snapshot_v1(jsonb,text,text,text,text,text,text) from public,anon,authenticated;
revoke all on function public.commerce_preview_ingest_shopee_snapshot_v1(jsonb,text,text,text,text,text,text) from public,anon,authenticated;
revoke all on function public.commerce_list_shopee_snapshot_v1(text,text,integer,integer) from public,anon,authenticated;
revoke all on function public.commerce_preview_list_shopee_snapshot_v1(text,text,integer,integer) from public,anon,authenticated;
revoke all on function public.commerce_list_products_v2(text,text,bigint,text,integer,integer) from public,anon,authenticated;
revoke all on function public.commerce_preview_list_products_v2(text,text,bigint,text,integer,integer) from public,anon,authenticated;
revoke all on function public.commerce_list_listings_v2(text,text,text,integer,integer) from public,anon,authenticated;
revoke all on function public.commerce_preview_list_listings_v2(text,text,text,integer,integer) from public,anon,authenticated;

grant execute on function public.commerce_ingest_shopee_snapshot_v1(jsonb,text,text,text,text,text,text) to service_role;
grant execute on function public.commerce_preview_ingest_shopee_snapshot_v1(jsonb,text,text,text,text,text,text) to service_role;
grant execute on function public.commerce_list_shopee_snapshot_v1(text,text,integer,integer) to service_role;
grant execute on function public.commerce_preview_list_shopee_snapshot_v1(text,text,integer,integer) to service_role;
grant execute on function public.commerce_list_products_v2(text,text,bigint,text,integer,integer) to service_role;
grant execute on function public.commerce_preview_list_products_v2(text,text,bigint,text,integer,integer) to service_role;
grant execute on function public.commerce_list_listings_v2(text,text,text,integer,integer) to service_role;
grant execute on function public.commerce_preview_list_listings_v2(text,text,text,integer,integer) to service_role;

commit;
