CREATE TABLE IF NOT EXISTS public.product_gtins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  gtin TEXT NOT NULL UNIQUE CHECK (gtin ~ '^[0-9]{13}$'),
  gtin_type TEXT NOT NULL DEFAULT 'GTIN-13' CHECK (gtin_type = 'GTIN-13'),
  source TEXT NOT NULL DEFAULT 'GS1' CHECK (source = 'GS1'),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_product_gtins_product_active
  ON public.product_gtins(product_id, active);

ALTER TABLE public.product_gtins ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.product_gtins FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.product_gtins TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.product_gtins_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.nisti_product_by_gtin(p_gtin TEXT, p_platform TEXT)
RETURNS TABLE (
  id BIGINT,
  sku TEXT,
  nome TEXT,
  capa_code TEXT,
  image_key TEXT,
  platform TEXT,
  link TEXT,
  gtin TEXT,
  gtin_type TEXT
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = ''
AS $$
  SELECT p.id, p.sku, p.nome, p.capa_code, p.image_key,
         pp.platform, pp.link, g.gtin, g.gtin_type
  FROM public.product_gtins g
  JOIN public.products p ON p.id = g.product_id
  JOIN public.product_platforms pp ON pp.product_id = p.id
  WHERE g.gtin = p_gtin
    AND g.active = TRUE
    AND upper(trim(pp.platform)) = upper(trim(p_platform))
  LIMIT 1;
$$;

REVOKE ALL ON FUNCTION public.nisti_product_by_gtin(TEXT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.nisti_product_by_gtin(TEXT, TEXT) TO service_role;
