begin;

create table if not exists public.commerce_product_state_events (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.commerce_products(id) on delete cascade,
  previous_status text not null,
  new_status text not null,
  checked_by text,
  created_at timestamptz not null default now(),
  constraint commerce_product_state_events_previous_status_ck
    check (previous_status in ('DRAFT','ACTIVE','DISCONTINUED')),
  constraint commerce_product_state_events_new_status_ck
    check (new_status in ('DRAFT','ACTIVE','DISCONTINUED'))
);

create index if not exists commerce_product_state_events_product_created_idx
  on public.commerce_product_state_events(product_id, created_at desc);

create table if not exists public.commerce_preview_product_state_events (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.commerce_preview_products(id) on delete cascade,
  previous_status text not null,
  new_status text not null,
  checked_by text,
  created_at timestamptz not null default now(),
  constraint commerce_preview_product_state_events_previous_status_ck
    check (previous_status in ('DRAFT','ACTIVE','DISCONTINUED')),
  constraint commerce_preview_product_state_events_new_status_ck
    check (new_status in ('DRAFT','ACTIVE','DISCONTINUED'))
);

create index if not exists commerce_preview_product_state_events_product_created_idx
  on public.commerce_preview_product_state_events(product_id, created_at desc);

create or replace function public.commerce_set_product_state_v1(
  p_product_id bigint,
  p_internal_status text,
  p_checked_by text default null
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_status text := nullif(upper(btrim(coalesce(p_internal_status, ''))), '');
  v_previous text;
  v_result jsonb;
begin
  if p_product_id is null or p_product_id <= 0 then
    raise exception 'product_id_invalid' using errcode = '22023';
  end if;

  if v_status is null or v_status not in ('DRAFT', 'ACTIVE', 'DISCONTINUED') then
    raise exception 'product_status_invalid' using errcode = '22023';
  end if;

  select internal_status
  into v_previous
  from public.commerce_products
  where id = p_product_id
  for update;

  if v_previous is null then
    raise exception 'product_not_found' using errcode = '22023';
  end if;

  if v_previous <> v_status then
    update public.commerce_products
    set internal_status = v_status,
        updated_at = now()
    where id = p_product_id;

    insert into public.commerce_product_state_events(
      product_id, previous_status, new_status, checked_by
    )
    values (
      p_product_id,
      v_previous,
      v_status,
      nullif(btrim(coalesce(p_checked_by, '')), '')
    );
  end if;

  select jsonb_build_object(
    'id', id,
    'internal_status', internal_status,
    'updated_at', updated_at,
    'previous_status', v_previous,
    'changed', v_previous <> internal_status
  )
  into v_result
  from public.commerce_products
  where id = p_product_id;

  return v_result;
end;
$$;

create or replace function public.commerce_preview_set_product_state_v1(
  p_product_id bigint,
  p_internal_status text,
  p_checked_by text default null
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_status text := nullif(upper(btrim(coalesce(p_internal_status, ''))), '');
  v_previous text;
  v_result jsonb;
begin
  if p_product_id is null or p_product_id <= 0 then
    raise exception 'product_id_invalid' using errcode = '22023';
  end if;

  if v_status is null or v_status not in ('DRAFT', 'ACTIVE', 'DISCONTINUED') then
    raise exception 'product_status_invalid' using errcode = '22023';
  end if;

  select internal_status
  into v_previous
  from public.commerce_preview_products
  where id = p_product_id
  for update;

  if v_previous is null then
    raise exception 'product_not_found' using errcode = '22023';
  end if;

  if v_previous <> v_status then
    update public.commerce_preview_products
    set internal_status = v_status,
        updated_at = now()
    where id = p_product_id;

    insert into public.commerce_preview_product_state_events(
      product_id, previous_status, new_status, checked_by
    )
    values (
      p_product_id,
      v_previous,
      v_status,
      nullif(btrim(coalesce(p_checked_by, '')), '')
    );
  end if;

  select jsonb_build_object(
    'id', id,
    'internal_status', internal_status,
    'updated_at', updated_at,
    'previous_status', v_previous,
    'changed', v_previous <> internal_status
  )
  into v_result
  from public.commerce_preview_products
  where id = p_product_id;

  return v_result;
end;
$$;

revoke all on function public.commerce_set_product_state_v1(bigint, text, text)
  from public, anon, authenticated;
grant execute on function public.commerce_set_product_state_v1(bigint, text, text)
  to service_role;

revoke all on function public.commerce_preview_set_product_state_v1(bigint, text, text)
  from public, anon, authenticated;
grant execute on function public.commerce_preview_set_product_state_v1(bigint, text, text)
  to service_role;

revoke all on table public.commerce_product_state_events
  from public, anon, authenticated;
grant select, insert on table public.commerce_product_state_events to service_role;
grant usage, select on sequence public.commerce_product_state_events_id_seq to service_role;

revoke all on table public.commerce_preview_product_state_events
  from public, anon, authenticated;
grant select, insert on table public.commerce_preview_product_state_events to service_role;
grant usage, select on sequence public.commerce_preview_product_state_events_id_seq to service_role;

commit;
