begin;

-- Arquivo de origem permanente. O Google Drive/Excel é somente a fonte da
-- migração: depois da ingestão, o catálogo não depende do arquivo externo.
create table if not exists public.commerce_source_files (
  id bigint generated by default as identity primary key,
  source_code text not null,
  source_name text not null,
  source_kind text not null,
  marketplace_code text,
  account_code text,
  source_filename text not null,
  source_sha256 text,
  source_modified_at timestamptz,
  row_count integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  imported_at timestamptz not null default now(),
  constraint commerce_source_files_code_nonblank check (btrim(source_code) <> ''),
  constraint commerce_source_files_name_nonblank check (btrim(source_name) <> ''),
  constraint commerce_source_files_filename_nonblank check (btrim(source_filename) <> ''),
  constraint commerce_source_files_kind_ck check (source_kind in ('PLATFORM_CATALOG','VARIATIONS','VIDEO_CONTROL')),
  constraint commerce_source_files_sha_ck check (source_sha256 is null or source_sha256 ~ '^[0-9a-fA-F]{64}$'),
  constraint commerce_source_files_row_count_ck check (row_count >= 0)
);

create unique index if not exists commerce_source_files_code_sha_idx
  on public.commerce_source_files (upper(btrim(source_code)), coalesce(lower(source_sha256), ''));

create table if not exists public.commerce_source_rows (
  id bigint generated by default as identity primary key,
  source_file_id bigint not null references public.commerce_source_files(id) on delete cascade,
  sheet_name text not null,
  row_number integer not null,
  is_header boolean not null default false,
  original_payload jsonb not null default '{}'::jsonb,
  normalized_payload jsonb not null default '{}'::jsonb,
  matched_product_id bigint references public.commerce_products(id) on delete set null,
  matched_listing_id bigint references public.commerce_listings(id) on delete set null,
  resolution_status text not null default 'RAW',
  notes text,
  imported_at timestamptz not null default now(),
  constraint commerce_source_rows_sheet_nonblank check (btrim(sheet_name) <> ''),
  constraint commerce_source_rows_row_number_ck check (row_number > 0),
  constraint commerce_source_rows_resolution_ck check (resolution_status in ('RAW','PRODUCT_MATCHED','LISTING_MATCHED','REFERENCE_ONLY','UNMATCHED','VARIATION','VIDEO_CONTROL')),
  unique (source_file_id, sheet_name, row_number)
);

create index if not exists commerce_source_rows_product_idx
  on public.commerce_source_rows (matched_product_id, source_file_id)
  where matched_product_id is not null;
create index if not exists commerce_source_rows_listing_idx
  on public.commerce_source_rows (matched_listing_id, source_file_id)
  where matched_listing_id is not null;
create index if not exists commerce_source_rows_source_resolution_idx
  on public.commerce_source_rows (source_file_id, resolution_status, sheet_name, row_number);

-- Espelho estrutural do sandbox gratuito.
create table if not exists public.commerce_preview_source_files
  (like public.commerce_source_files including all);
create table if not exists public.commerce_preview_source_rows
  (like public.commerce_source_rows including all);

-- LIKE não deve ser usado como substituto implícito de integridade referencial.
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'commerce_preview_source_rows_source_file_fk') then
    alter table public.commerce_preview_source_rows
      add constraint commerce_preview_source_rows_source_file_fk
      foreign key (source_file_id) references public.commerce_preview_source_files(id) on delete cascade;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'commerce_preview_source_rows_product_fk') then
    alter table public.commerce_preview_source_rows
      add constraint commerce_preview_source_rows_product_fk
      foreign key (matched_product_id) references public.commerce_preview_products(id) on delete set null;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'commerce_preview_source_rows_listing_fk') then
    alter table public.commerce_preview_source_rows
      add constraint commerce_preview_source_rows_listing_fk
      foreign key (matched_listing_id) references public.commerce_preview_listings(id) on delete set null;
  end if;
end;
$$;

-- Corrige os defaults de identidade das tabelas clonadas para sequências próprias.
do $$
declare
  seq_name text;
begin
  if pg_get_serial_sequence('public.commerce_preview_source_files', 'id') is null then
    create sequence if not exists public.commerce_preview_source_files_id_seq;
    alter sequence public.commerce_preview_source_files_id_seq owned by public.commerce_preview_source_files.id;
    alter table public.commerce_preview_source_files alter column id set default nextval('public.commerce_preview_source_files_id_seq');
  end if;
  if pg_get_serial_sequence('public.commerce_preview_source_rows', 'id') is null then
    create sequence if not exists public.commerce_preview_source_rows_id_seq;
    alter sequence public.commerce_preview_source_rows_id_seq owned by public.commerce_preview_source_rows.id;
    alter table public.commerce_preview_source_rows alter column id set default nextval('public.commerce_preview_source_rows_id_seq');
  end if;
end;
$$;

-- Segurança server-only, igual ao restante do Catálogo Comercial.
do $$
declare
  t text;
  seq_name text;
begin
  foreach t in array array[
    'commerce_source_files','commerce_source_rows',
    'commerce_preview_source_files','commerce_preview_source_rows'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on table public.%I from public, anon, authenticated', t);
    execute format('grant all on table public.%I to service_role', t);
    seq_name := pg_get_serial_sequence(format('public.%I', t), 'id');
    if seq_name is not null then
      execute format('grant usage, select on sequence %s to service_role', seq_name);
    end if;
  end loop;
end;
$$;

commit;
